/**
 * Finnish sentence database for reading practice.
 * Each sentence has: sentence (uppercase), translation (English), translation_es (Spanish), translation_sv (Swedish), difficulty.
 */

export const sentences = [
  // ============================================================
  // EASY (~35) — 3-5 words, simple structure
  // ============================================================
  { sentence: 'KISSA NUKKUU.', translation: 'The cat is sleeping.', translation_es: 'El gato está durmiendo.', translation_sv: 'Katten sover.', difficulty: 'easy' },
  { sentence: 'KOIRA JUOKSEE.', translation: 'The dog is running.', translation_es: 'El perro está corriendo.', translation_sv: 'Hunden springer.', difficulty: 'easy' },
  { sentence: 'LINTU LAULAA.', translation: 'The bird is singing.', translation_es: 'El pájaro está cantando.', translation_sv: 'Fågeln sjunger.', difficulty: 'easy' },
  { sentence: 'LAPSI LEIKKII.', translation: 'The child is playing.', translation_es: 'El niño está jugando.', translation_sv: 'Barnet leker.', difficulty: 'easy' },
  { sentence: 'ÄITI LUKEE.', translation: 'Mother is reading.', translation_es: 'La madre está leyendo.', translation_sv: 'Mamma läser.', difficulty: 'easy' },
  { sentence: 'ISÄ KEITTÄÄ.', translation: 'Father is cooking.', translation_es: 'El padre está cocinando.', translation_sv: 'Pappa lagar mat.', difficulty: 'easy' },
  { sentence: 'VAUVA ITKEE.', translation: 'The baby is crying.', translation_es: 'El bebé está llorando.', translation_sv: 'Bebisen gråter.', difficulty: 'easy' },
  { sentence: 'TYTTÖ TANSSII.', translation: 'The girl is dancing.', translation_es: 'La chica está bailando.', translation_sv: 'Flickan dansar.', difficulty: 'easy' },
  { sentence: 'POIKA PIIRTÄÄ.', translation: 'The boy is drawing.', translation_es: 'El chico está dibujando.', translation_sv: 'Pojken ritar.', difficulty: 'easy' },
  { sentence: 'KALA UI.', translation: 'The fish is swimming.', translation_es: 'El pez está nadando.', translation_sv: 'Fisken simmar.', difficulty: 'easy' },
  { sentence: 'AURINKO PAISTAA.', translation: 'The sun is shining.', translation_es: 'El sol está brillando.', translation_sv: 'Solen skiner.', difficulty: 'easy' },
  { sentence: 'LUMI SATAA.', translation: 'It is snowing.', translation_es: 'Está nevando.', translation_sv: 'Det snöar.', difficulty: 'easy' },
  { sentence: 'TUULI PUHALTAA.', translation: 'The wind is blowing.', translation_es: 'El viento está soplando.', translation_sv: 'Vinden blåser.', difficulty: 'easy' },
  { sentence: 'KUKKA KASVAA.', translation: 'The flower is growing.', translation_es: 'La flor está creciendo.', translation_sv: 'Blomman växer.', difficulty: 'easy' },
  { sentence: 'HIIRI SYÖDÄ JUUSTOA.', translation: 'The mouse eats cheese.', translation_es: 'El ratón come queso.', translation_sv: 'Musen äter ost.', difficulty: 'easy' },
  { sentence: 'KOIRA ON ISO.', translation: 'The dog is big.', translation_es: 'El perro es grande.', translation_sv: 'Hunden är stor.', difficulty: 'easy' },
  { sentence: 'KISSA ON PIENI.', translation: 'The cat is small.', translation_es: 'El gato es pequeño.', translation_sv: 'Katten är liten.', difficulty: 'easy' },
  { sentence: 'VESI ON KYLMÄÄ.', translation: 'The water is cold.', translation_es: 'El agua está fría.', translation_sv: 'Vattnet är kallt.', difficulty: 'easy' },
  { sentence: 'TULI ON KUUMAA.', translation: 'The fire is hot.', translation_es: 'El fuego está caliente.', translation_sv: 'Elden är het.', difficulty: 'easy' },
  { sentence: 'PALLO ON PUNAINEN.', translation: 'The ball is red.', translation_es: 'La pelota es roja.', translation_sv: 'Bollen är röd.', difficulty: 'easy' },
  { sentence: 'TAIVAS ON SININEN.', translation: 'The sky is blue.', translation_es: 'El cielo es azul.', translation_sv: 'Himlen är blå.', difficulty: 'easy' },
  { sentence: 'RUOHO ON VIHREÄÄ.', translation: 'The grass is green.', translation_es: 'La hierba es verde.', translation_sv: 'Gräset är grönt.', difficulty: 'easy' },
  { sentence: 'MINÄ RAKASTAN SINUA.', translation: 'I love you.', translation_es: 'Te quiero.', translation_sv: 'Jag älskar dig.', difficulty: 'easy' },
  { sentence: 'HYVÄÄ HUOMENTA!', translation: 'Good morning!', translation_es: '¡Buenos días!', translation_sv: 'God morgon!', difficulty: 'easy' },
  { sentence: 'HYVÄÄ YÖTÄ!', translation: 'Good night!', translation_es: '¡Buenas noches!', translation_sv: 'God natt!', difficulty: 'easy' },
  { sentence: 'KIITOS PALJON!', translation: 'Thank you very much!', translation_es: '¡Muchas gracias!', translation_sv: 'Tack så mycket!', difficulty: 'easy' },
  { sentence: 'OVI ON AUKI.', translation: 'The door is open.', translation_es: 'La puerta está abierta.', translation_sv: 'Dörren är öppen.', difficulty: 'easy' },
  { sentence: 'SAMMAKKO HYPPÄÄ.', translation: 'The frog is jumping.', translation_es: 'La rana está saltando.', translation_sv: 'Grodan hoppar.', difficulty: 'easy' },
  { sentence: 'JÄNIS ON NOPEA.', translation: 'The rabbit is fast.', translation_es: 'El conejo es rápido.', translation_sv: 'Kaninen är snabb.', difficulty: 'easy' },
  { sentence: 'KARHU NUKKUU TALVELLA.', translation: 'The bear sleeps in winter.', translation_es: 'El oso duerme en invierno.', translation_sv: 'Björnen sover på vintern.', difficulty: 'easy' },
  { sentence: 'TÄHDET LOISTAVAT.', translation: 'The stars are shining.', translation_es: 'Las estrellas brillan.', translation_sv: 'Stjärnorna lyser.', difficulty: 'easy' },
  { sentence: 'LAPSET NAURAVAT.', translation: 'The children are laughing.', translation_es: 'Los niños se ríen.', translation_sv: 'Barnen skrattar.', difficulty: 'easy' },
  { sentence: 'SADE TULEE.', translation: 'The rain is coming.', translation_es: 'La lluvia está llegando.', translation_sv: 'Regnet kommer.', difficulty: 'easy' },
  { sentence: 'KOIRA HAUKKUU.', translation: 'The dog is barking.', translation_es: 'El perro está ladrando.', translation_sv: 'Hunden skäller.', difficulty: 'easy' },
  { sentence: 'KISSA KEHRÄÄ.', translation: 'The cat is purring.', translation_es: 'El gato está ronroneando.', translation_sv: 'Katten spinner.', difficulty: 'easy' },
  { sentence: 'PERHE SYÖDÄ YHDESSÄ.', translation: 'The family eats together.', translation_es: 'La familia come junta.', translation_sv: 'Familjen äter tillsammans.', difficulty: 'easy' },

  // ============================================================
  // MEDIUM (~35) — 5-8 words, more complex structure
  // ============================================================
  { sentence: 'PUNAINEN KETTU JUOKSEE METSÄSSÄ.', translation: 'The red fox runs in the forest.', translation_es: 'El zorro rojo corre en el bosque.', translation_sv: 'Den röda räven springer i skogen.', difficulty: 'medium' },
  { sentence: 'LAPSET LEIKKIVÄT PUISTOSSA YHDESSÄ.', translation: 'The children play together in the park.', translation_es: 'Los niños juegan juntos en el parque.', translation_sv: 'Barnen leker tillsammans i parken.', difficulty: 'medium' },
  { sentence: 'ÄITI LEIPOO KAKKUA KEITTIÖSSÄ.', translation: 'Mother is baking a cake in the kitchen.', translation_es: 'La madre está horneando un pastel en la cocina.', translation_sv: 'Mamma bakar en tårta i köket.', difficulty: 'medium' },
  { sentence: 'ISÄ LUKEE SANOMALEHTEÄ AAMUISIN.', translation: 'Father reads the newspaper in the mornings.', translation_es: 'El padre lee el periódico por las mañanas.', translation_sv: 'Pappa läser tidningen på morgnarna.', difficulty: 'medium' },
  { sentence: 'KOIRA JUOKSEE NOPEASTI PUISTOSSA.', translation: 'The dog runs fast in the park.', translation_es: 'El perro corre rápido en el parque.', translation_sv: 'Hunden springer snabbt i parken.', difficulty: 'medium' },
  { sentence: 'LINNUT LENTÄVÄT ETELÄÄN SYKSYLLÄ.', translation: 'The birds fly south in autumn.', translation_es: 'Los pájaros vuelan al sur en otoño.', translation_sv: 'Fåglarna flyger söderut på hösten.', difficulty: 'medium' },
  { sentence: 'KISSA ISTUU IKKUNALLA JA KATSOO.', translation: 'The cat sits on the window and watches.', translation_es: 'El gato se sienta en la ventana y observa.', translation_sv: 'Katten sitter i fönstret och tittar.', difficulty: 'medium' },
  { sentence: 'TYTTÖ SOITTAA PIANOA JOKA PÄIVÄ.', translation: 'The girl plays piano every day.', translation_es: 'La chica toca el piano todos los días.', translation_sv: 'Flickan spelar piano varje dag.', difficulty: 'medium' },
  { sentence: 'POIKA PELAA JALKAPALLOA KENTÄLLÄ.', translation: 'The boy plays football on the field.', translation_es: 'El chico juega al fútbol en el campo.', translation_sv: 'Pojken spelar fotboll på planen.', difficulty: 'medium' },
  { sentence: 'ME MENEMME KAUPPAAN TÄNÄÄN.', translation: 'We are going to the store today.', translation_es: 'Hoy vamos a la tienda.', translation_sv: 'Vi går till affären idag.', difficulty: 'medium' },
  { sentence: 'AURINKO NOUSEE IDÄSTÄ JOKA AAMU.', translation: 'The sun rises from the east every morning.', translation_es: 'El sol sale por el este cada mañana.', translation_sv: 'Solen stiger i öster varje morgon.', difficulty: 'medium' },
  { sentence: 'PERHONEN LENTÄÄ KUKASTA KUKKAAN.', translation: 'The butterfly flies from flower to flower.', translation_es: 'La mariposa vuela de flor en flor.', translation_sv: 'Fjärilen flyger från blomma till blomma.', difficulty: 'medium' },
  { sentence: 'OPETTAJA SELITTÄÄ LÄKSYN SELKEÄSTI.', translation: 'The teacher explains the homework clearly.', translation_es: 'El profesor explica la tarea claramente.', translation_sv: 'Läraren förklarar läxan tydligt.', difficulty: 'medium' },
  { sentence: 'LAPSI PIIRTÄÄ KAUNIIN KUVAN PAPERILLE.', translation: 'The child draws a beautiful picture on paper.', translation_es: 'El niño dibuja una imagen bonita en papel.', translation_sv: 'Barnet ritar en vacker bild på papper.', difficulty: 'medium' },
  { sentence: 'VANHA PUU KASVAA PIHAN KESKELLÄ.', translation: 'An old tree grows in the middle of the yard.', translation_es: 'Un viejo árbol crece en medio del patio.', translation_sv: 'Ett gammalt träd växer mitt på gården.', difficulty: 'medium' },
  { sentence: 'MUMMO NEULOO VILLASUKKIA ILLALLA.', translation: 'Grandma knits wool socks in the evening.', translation_es: 'La abuela teje calcetines de lana por la noche.', translation_sv: 'Mormor stickar yllestrumpor på kvällen.', difficulty: 'medium' },
  { sentence: 'VAARI KERTOO TARINOITA LAPSILLE.', translation: 'Grandpa tells stories to the children.', translation_es: 'El abuelo cuenta historias a los niños.', translation_sv: 'Morfar berättar sagor för barnen.', difficulty: 'medium' },
  { sentence: 'SAMMAKKO HYPPÄÄ LAMMESTA KIVELLE.', translation: 'The frog jumps from the pond to a rock.', translation_es: 'La rana salta del estanque a una roca.', translation_sv: 'Grodan hoppar från dammen till en sten.', difficulty: 'medium' },
  { sentence: 'JUNA SAAPUU ASEMALLE AJOISSA.', translation: 'The train arrives at the station on time.', translation_es: 'El tren llega a la estación a tiempo.', translation_sv: 'Tåget anländer till stationen i tid.', difficulty: 'medium' },
  { sentence: 'LAIVA PURJEHTII MERELLÄ HITAASTI.', translation: 'The ship sails slowly on the sea.', translation_es: 'El barco navega lentamente por el mar.', translation_sv: 'Skeppet seglar långsamt på havet.', difficulty: 'medium' },
  { sentence: 'PIENI HIIRI PIILOUTUU KOLOONSA.', translation: 'The little mouse hides in its hole.', translation_es: 'El pequeño ratón se esconde en su agujero.', translation_sv: 'Den lilla musen gömmer sig i sitt hål.', difficulty: 'medium' },
  { sentence: 'KOULU ALKAA AAMULLA KAHDEKSALTA.', translation: 'School starts in the morning at eight.', translation_es: 'La escuela empieza por la mañana a las ocho.', translation_sv: 'Skolan börjar på morgonen klockan åtta.', difficulty: 'medium' },
  { sentence: 'KIRJASTO ON HILJAINEN PAIKKA LUKEA.', translation: 'The library is a quiet place to read.', translation_es: 'La biblioteca es un lugar tranquilo para leer.', translation_sv: 'Biblioteket är en lugn plats att läsa.', difficulty: 'medium' },
  { sentence: 'SATEENKAARI NÄKYY SATEEN JÄLKEEN.', translation: 'A rainbow is visible after the rain.', translation_es: 'Un arcoíris es visible después de la lluvia.', translation_sv: 'En regnbåge syns efter regnet.', difficulty: 'medium' },
  { sentence: 'KETTU ETSII RUOKAA ILLALLA METSÄSTÄ.', translation: 'The fox looks for food in the forest in the evening.', translation_es: 'El zorro busca comida en el bosque por la noche.', translation_sv: 'Räven letar efter mat i skogen på kvällen.', difficulty: 'medium' },
  { sentence: 'TYTÖT UIVAT JÄRVESSÄ KESÄLLÄ.', translation: 'The girls swim in the lake in summer.', translation_es: 'Las chicas nadan en el lago en verano.', translation_sv: 'Flickorna simmar i sjön på sommaren.', difficulty: 'medium' },
  { sentence: 'POJAT KIIPEILEVÄT PUISSA LEIKKIEN.', translation: 'The boys climb trees while playing.', translation_es: 'Los chicos trepan a los árboles mientras juegan.', translation_sv: 'Pojkarna klättrar i träd medan de leker.', difficulty: 'medium' },
  { sentence: 'HEVONEN LAUKKAA NIITYLLÄ VAPAASTI.', translation: 'The horse gallops freely in the meadow.', translation_es: 'El caballo galopa libremente en el prado.', translation_sv: 'Hästen galopperar fritt på ängen.', difficulty: 'medium' },
  { sentence: 'ORAVA KERÄÄ PÄHKINÖITÄ SYKSYLLÄ.', translation: 'The squirrel collects nuts in autumn.', translation_es: 'La ardilla recoge nueces en otoño.', translation_sv: 'Ekorren samlar nötter på hösten.', difficulty: 'medium' },
  { sentence: 'ISOÄITI ASUU PUNAISESSA TALOSSA.', translation: 'Grandmother lives in a red house.', translation_es: 'La abuela vive en una casa roja.', translation_sv: 'Mormor bor i ett rött hus.', difficulty: 'medium' },
  { sentence: 'MINÄ PIDÄN JÄÄTELÖSTÄ KESÄLLÄ.', translation: 'I like ice cream in summer.', translation_es: 'Me gusta el helado en verano.', translation_sv: 'Jag tycker om glass på sommaren.', difficulty: 'medium' },
  { sentence: 'ME MATKUSTAMME JUNALLA KAUPUNKIIN.', translation: 'We travel by train to the city.', translation_es: 'Viajamos en tren a la ciudad.', translation_sv: 'Vi reser med tåg till staden.', difficulty: 'medium' },
  { sentence: 'KOIRA ODOTTAA OMISTAJAANSA KOTONA.', translation: 'The dog waits for its owner at home.', translation_es: 'El perro espera a su dueño en casa.', translation_sv: 'Hunden väntar på sin ägare hemma.', difficulty: 'medium' },
  { sentence: 'PÖLLÖ VALVOO YÖLLÄ METSÄSSÄ.', translation: 'The owl stays awake at night in the forest.', translation_es: 'El búho está despierto por la noche en el bosque.', translation_sv: 'Ugglan är vaken på natten i skogen.', difficulty: 'medium' },
  { sentence: 'KISSANPENTU LEIKKII LANKAKERÄLLÄ.', translation: 'The kitten plays with a ball of yarn.', translation_es: 'El gatito juega con un ovillo de lana.', translation_sv: 'Kattungen leker med ett garnnystan.', difficulty: 'medium' },

  // ============================================================
  // HARD (~35) — 8+ words, compound structures
  // ============================================================
  { sentence: 'PIENI PUNAINEN KETTU JUOKSEE NOPEASTI LÄPI PIMEÄN METSÄN.', translation: 'The small red fox runs quickly through the dark forest.', translation_es: 'El pequeño zorro rojo corre rápidamente a través del bosque oscuro.', translation_sv: 'Den lilla röda räven springer snabbt genom den mörka skogen.', difficulty: 'hard' },
  { sentence: 'LAPSET RAKENTAVAT ISON LUMIUKON PIHALLE TALVIPÄIVÄNÄ.', translation: 'The children build a big snowman in the yard on a winter day.', translation_es: 'Los niños construyen un gran muñeco de nieve en el patio en un día de invierno.', translation_sv: 'Barnen bygger en stor snögubbe på gården en vinterdag.', difficulty: 'hard' },
  { sentence: 'ÄITI JA ISÄ VALMISTAVAT YHDESSÄ HERKULLISEN ILLALLISEN PERHEELLE.', translation: 'Mother and father prepare a delicious dinner for the family together.', translation_es: 'La madre y el padre preparan juntos una deliciosa cena para la familia.', translation_sv: 'Mamma och pappa lagar en läcker middag åt familjen tillsammans.', difficulty: 'hard' },
  { sentence: 'VANHA VIISAS PÖLLÖ ISTUU KORKEALLA PUUSSA JA TARKKAILEE METSÄÄ.', translation: 'The old wise owl sits high in a tree and watches the forest.', translation_es: 'El viejo búho sabio se sienta en lo alto de un árbol y observa el bosque.', translation_sv: 'Den gamla visa ugglan sitter högt i ett träd och betraktar skogen.', difficulty: 'hard' },
  { sentence: 'KAUNIS PERHONEN LENTÄÄ HITAASTI VÄRIKKÄIDEN KUKKIEN YLLÄ PUUTARHASSA.', translation: 'A beautiful butterfly flies slowly over the colorful flowers in the garden.', translation_es: 'Una hermosa mariposa vuela lentamente sobre las flores coloridas en el jardín.', translation_sv: 'En vacker fjäril flyger långsamt över de färgglada blommorna i trädgården.', difficulty: 'hard' },
  { sentence: 'KESÄISIN PERHE MATKUSTAA MÖKILLE JÄRVEN RANNALLE RENTOUTUMAAN.', translation: 'In summers the family travels to the cottage by the lake to relax.', translation_es: 'En verano la familia viaja a la cabaña junto al lago para relajarse.', translation_sv: 'På somrarna reser familjen till stugan vid sjön för att koppla av.', difficulty: 'hard' },
  { sentence: 'ROHKEA PIENI HIIRI SEIKKAILEE VANHASSA TALOSSA ETSIEN JUUSTOA.', translation: 'The brave little mouse adventures in the old house looking for cheese.', translation_es: 'El valiente ratoncito se aventura en la vieja casa buscando queso.', translation_sv: 'Den modiga lilla musen äventyrar i det gamla huset och letar efter ost.', difficulty: 'hard' },
  { sentence: 'OPPILAAT OPISKELEVAT AHKERASTI KOKEESEEN KIRJASTOSSA ILTAPÄIVÄLLÄ.', translation: 'The students study diligently for the exam in the library in the afternoon.', translation_es: 'Los estudiantes estudian diligentemente para el examen en la biblioteca por la tarde.', translation_sv: 'Eleverna studerar flitigt inför provet på biblioteket på eftermiddagen.', difficulty: 'hard' },
  { sentence: 'TALVELLA LAPSET LASKEVAT MÄKEÄ JA TEKEVÄT LUMIENKELEITÄ PIHALLA.', translation: 'In winter the children sled and make snow angels in the yard.', translation_es: 'En invierno los niños se deslizan en trineo y hacen ángeles de nieve en el patio.', translation_sv: 'På vintern åker barnen pulka och gör snöänglar på gården.', difficulty: 'hard' },
  { sentence: 'ISOÄITI KERTOO JÄNNITTÄVIÄ TARINOITA MENNEISTÄ AJOISTA TAKKATULEN ÄÄRESSÄ.', translation: 'Grandmother tells exciting stories of past times by the fireplace.', translation_es: 'La abuela cuenta emocionantes historias de tiempos pasados junto a la chimenea.', translation_sv: 'Mormor berättar spännande historier om förflutna tider vid brasan.', difficulty: 'hard' },
  { sentence: 'KALASTAJA ISTUU RAUHALLISESTI VENEESSÄ JA ODOTTAA KALAN NAPPAAMISTA.', translation: 'The fisherman sits calmly in the boat and waits for a fish to bite.', translation_es: 'El pescador se sienta tranquilamente en el bote y espera que un pez muerda.', translation_sv: 'Fiskaren sitter lugnt i båten och väntar på att en fisk ska nappa.', difficulty: 'hard' },
  { sentence: 'AAMULLA HERÄTTYÄÄN LAPSI PESEE KASVONSA JA HARJAA HAMPAANSA.', translation: 'After waking up in the morning the child washes their face and brushes their teeth.', translation_es: 'Después de despertarse por la mañana, el niño se lava la cara y se cepilla los dientes.', translation_sv: 'Efter att ha vaknat på morgonen tvättar barnet ansiktet och borstar tänderna.', difficulty: 'hard' },
  { sentence: 'PIENI KOIRANPENTU OPETTELEE KÄVELEMÄÄN ENSIMMÄISTÄ KERTAA NURMIKOLLA.', translation: 'The little puppy learns to walk for the first time on the lawn.', translation_es: 'El pequeño cachorro aprende a caminar por primera vez en el césped.', translation_sv: 'Den lilla valpen lär sig gå för första gången på gräsmattan.', difficulty: 'hard' },
  { sentence: 'SATEELLA LAPSET PUKEVAT KUMISAAPPAAT JA HYPPIVÄT LÄTÄKÖISSÄ ILOISESTI.', translation: 'In the rain the children put on rain boots and jump happily in puddles.', translation_es: 'Bajo la lluvia los niños se ponen botas de lluvia y saltan alegremente en los charcos.', translation_sv: 'I regnet tar barnen på sig gummistövlar och hoppar glatt i pölarna.', difficulty: 'hard' },
  { sentence: 'TAITAVA KOKKI VALMISTAA MAUKASTA RUOKAA TUOREISTA RAAKA-AINEISTA RAVINTOLASSA.', translation: 'The skilled chef prepares tasty food from fresh ingredients in the restaurant.', translation_es: 'El hábil chef prepara comida sabrosa con ingredientes frescos en el restaurante.', translation_sv: 'Den skickliga kocken lagar god mat av färska ingredienser på restaurangen.', difficulty: 'hard' },
  { sentence: 'URHEILIJA HARJOITTELEE JOKA PÄIVÄ KOVASTI VALMISTAUTUAKSEEN KILPAILUUN.', translation: 'The athlete practices hard every day to prepare for the competition.', translation_es: 'El atleta practica duro todos los días para prepararse para la competición.', translation_sv: 'Idrottaren tränar hårt varje dag för att förbereda sig inför tävlingen.', difficulty: 'hard' },
  { sentence: 'TUTKIMUSMATKAILIJA LÖYSI UUDEN KASVILAJIN SYVÄLTÄ SADEMETSÄN SISÄLTÄ.', translation: 'The explorer found a new plant species deep inside the rainforest.', translation_es: 'El explorador encontró una nueva especie de planta en lo profundo de la selva tropical.', translation_sv: 'Upptäcktsresanden hittade en ny växtart djupt inne i regnskogen.', difficulty: 'hard' },
  { sentence: 'MUMMON PUUTARHASSA KASVAA MONIA ERILAISIA KUKKIA JA VIHANNEKSIA.', translation: 'Many different flowers and vegetables grow in grandma\'s garden.', translation_es: 'Muchas flores y verduras diferentes crecen en el jardín de la abuela.', translation_sv: 'Många olika blommor och grönsaker växer i mormors trädgård.', difficulty: 'hard' },
  { sentence: 'LAPSET KUUNTELEVAT TARKKAAVAISESTI KUN OPETTAJA LUKEE SATUA ÄÄNEEN.', translation: 'The children listen attentively when the teacher reads a fairy tale aloud.', translation_es: 'Los niños escuchan atentamente cuando el profesor lee un cuento en voz alta.', translation_sv: 'Barnen lyssnar uppmärksamt när läraren läser en saga högt.', difficulty: 'hard' },
  { sentence: 'PIENI SIILI KÄPERTYY PALLOKSI KUN SE PELKÄÄ JOTAKIN METSÄSSÄ.', translation: 'The little hedgehog curls into a ball when it fears something in the forest.', translation_es: 'El pequeño erizo se enrolla en una bola cuando teme algo en el bosque.', translation_sv: 'Den lilla igelkotten rullar ihop sig till en boll när den är rädd för något i skogen.', difficulty: 'hard' },
  { sentence: 'REVONTULET LOISTAVAT KAUNIISTI TAIVAALLA KIRKKAANA TALVI-ILTANA LAPISSA.', translation: 'The northern lights shine beautifully in the sky on a clear winter evening in Lapland.', translation_es: 'Las auroras boreales brillan hermosamente en el cielo en una clara noche de invierno en Laponia.', translation_sv: 'Norrskenet lyser vackert på himlen en klar vinterkväll i Lappland.', difficulty: 'hard' },
  { sentence: 'MERIMIES KATSOO HORISONTTIIN JA HAAVEILEE KAUKAISISTA MAISTA JA SEIKKAILUISTA.', translation: 'The sailor looks at the horizon and dreams of distant lands and adventures.', translation_es: 'El marinero mira al horizonte y sueña con tierras lejanas y aventuras.', translation_sv: 'Sjömannen tittar mot horisonten och drömmer om fjärran länder och äventyr.', difficulty: 'hard' },
  { sentence: 'AHKERA MUURAHAINEN KANTAA ISOA LEHTEÄ TAKAISIN PESÄÄNSÄ METSÄPOLULLA.', translation: 'The diligent ant carries a big leaf back to its nest on the forest path.', translation_es: 'La hormiga diligente lleva una gran hoja de vuelta a su nido en el sendero del bosque.', translation_sv: 'Den flitiga myran bär ett stort löv tillbaka till sitt bo på skogsstigen.', difficulty: 'hard' },
  { sentence: 'LAPSET OPPIVAT UUSIA ASIOITA JOKA PÄIVÄ KOULUSSA JA KOTONA.', translation: 'Children learn new things every day at school and at home.', translation_es: 'Los niños aprenden cosas nuevas todos los días en la escuela y en casa.', translation_sv: 'Barn lär sig nya saker varje dag i skolan och hemma.', difficulty: 'hard' },
  { sentence: 'VANHA TALO SEISOO YKSINÄÄN KUKKULAN PÄÄLLÄ TUULEN PUHALTAESSA.', translation: 'The old house stands alone on top of a hill as the wind blows.', translation_es: 'La vieja casa está sola en la cima de una colina mientras el viento sopla.', translation_sv: 'Det gamla huset står ensamt på toppen av en kulle medan vinden blåser.', difficulty: 'hard' },
  { sentence: 'JOULUAATTONA PERHE KOKOONTUU YHTEEN SYÖMÄÄN JA AVAAMAAN LAHJOJA.', translation: 'On Christmas Eve the family gathers together to eat and open presents.', translation_es: 'En Nochebuena la familia se reúne para comer y abrir regalos.', translation_sv: 'På julafton samlas familjen för att äta och öppna julklappar.', difficulty: 'hard' },
  { sentence: 'LUMIUKOLLA ON PORKKANANENÄ, KIVISIULMAT JA PITKÄ KAULAHUIVI.', translation: 'The snowman has a carrot nose, stone eyes and a long scarf.', translation_es: 'El muñeco de nieve tiene una nariz de zanahoria, ojos de piedra y una bufanda larga.', translation_sv: 'Snögubben har en morotsnäsa, stenögon och en lång halsduk.', difficulty: 'hard' },
  { sentence: 'KESÄMÖKILLÄ ISOISÄ OPETTAA LAPSENLAPSILLE KALASTAMISTA JÄRVELLÄ.', translation: 'At the summer cottage grandpa teaches the grandchildren fishing on the lake.', translation_es: 'En la cabaña de verano el abuelo enseña a los nietos a pescar en el lago.', translation_sv: 'På sommarstugan lär morfar barnbarnen att fiska på sjön.', difficulty: 'hard' },
  { sentence: 'YSTÄVYKSET SUUNNITTELEVAT YHDESSÄ JÄNNITTÄVÄÄ RETKEILYÄ KANSALLISPUISTOON.', translation: 'The friends plan an exciting hiking trip to the national park together.', translation_es: 'Los amigos planean juntos una emocionante excursión al parque nacional.', translation_sv: 'Vännerna planerar en spännande vandringstur till nationalparken tillsammans.', difficulty: 'hard' },
  { sentence: 'PIENI TIKKA KOPUTTAA PUUN RUNKOA ETSIESSÄÄN HYÖNTEISIÄ RAVINNOKSEEN.', translation: 'The little woodpecker taps the tree trunk while looking for insects to eat.', translation_es: 'El pequeño pájaro carpintero golpea el tronco del árbol mientras busca insectos para comer.', translation_sv: 'Den lilla hackspetten knackar på trädstammen medan den letar efter insekter att äta.', difficulty: 'hard' },
  { sentence: 'MAANVILJELIJÄ HERÄÄ AIKAISIN AAMULLA RUOKKIMAAN ELÄIMIÄ JA HOITAMAAN PELTOJA.', translation: 'The farmer wakes up early in the morning to feed the animals and tend the fields.', translation_es: 'El granjero se despierta temprano por la mañana para alimentar a los animales y cuidar los campos.', translation_sv: 'Bonden vaknar tidigt på morgonen för att mata djuren och sköta åkrarna.', difficulty: 'hard' },
  { sentence: 'KIRJAILIJA KIRJOITTAA UUTTA TARINAA RAUHALLISESSA HUONEESSAAN JOKA ILTA.', translation: 'The writer writes a new story in their quiet room every evening.', translation_es: 'El escritor escribe una nueva historia en su habitación tranquila cada noche.', translation_sv: 'Författaren skriver en ny berättelse i sitt lugna rum varje kväll.', difficulty: 'hard' },
  { sentence: 'ORKESTERI SOITTAA KAUNISTA MUSIIKKIA KONSERTISSA JA YLEISÖ KUUNTELEE HILJAA.', translation: 'The orchestra plays beautiful music at the concert and the audience listens quietly.', translation_es: 'La orquesta toca música hermosa en el concierto y el público escucha en silencio.', translation_sv: 'Orkestern spelar vacker musik på konserten och publiken lyssnar tyst.', difficulty: 'hard' },
  { sentence: 'AVARUUDESSA ON MILJOONIA TÄHTIÄ JA PLANEETTOJA JOITA EMME VOI NÄHDÄ.', translation: 'In space there are millions of stars and planets that we cannot see.', translation_es: 'En el espacio hay millones de estrellas y planetas que no podemos ver.', translation_sv: 'I rymden finns det miljontals stjärnor och planeter som vi inte kan se.', difficulty: 'hard' },
  { sentence: 'PIENI PURJEVENE KEINUU RAUHALLISESTI AALLOILLA AURINGON LASKIESSA HORISONTTIIN.', translation: 'A small sailboat rocks calmly on the waves as the sun sets on the horizon.', translation_es: 'Un pequeño velero se mece tranquilamente en las olas mientras el sol se pone en el horizonte.', translation_sv: 'En liten segelbåt vaggar lugnt på vågorna medan solen går ner vid horisonten.', difficulty: 'hard' },
];

/**
 * Get sentences filtered by difficulty level.
 * @param {string} difficulty - 'easy', 'medium', or 'hard'
 * @returns {Array} Filtered sentences
 */
export function getSentencesByDifficulty(difficulty) {
  return sentences.filter((s) => s.difficulty === difficulty);
}
