/**
 * Finnish word database for reading practice.
 * Each word has: word (uppercase), translation (English), difficulty, category.
 */

export const DIFFICULTY = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
};

export const CATEGORY = {
  NOUN: 'noun',
  VERB: 'verb',
  ADJECTIVE: 'adjective',
};

export const words = [
  // ============================================================
  // NOUNS
  // ============================================================

  // --- Easy nouns (~70) ---
  { word: 'KISSA', translation: 'cat', translation_es: 'gato', translation_sv: 'katt', difficulty: 'easy', category: 'noun' },
  { word: 'KOIRA', translation: 'dog', translation_es: 'perro', translation_sv: 'hund', difficulty: 'easy', category: 'noun' },
  { word: 'AUTO', translation: 'car', translation_es: 'coche', translation_sv: 'bil', difficulty: 'easy', category: 'noun' },
  { word: 'TALO', translation: 'house', translation_es: 'casa', translation_sv: 'hus', difficulty: 'easy', category: 'noun' },
  { word: 'PUU', translation: 'tree', translation_es: 'árbol', translation_sv: 'träd', difficulty: 'easy', category: 'noun' },
  { word: 'SUU', translation: 'mouth', translation_es: 'boca', translation_sv: 'mun', difficulty: 'easy', category: 'noun' },
  { word: 'TIE', translation: 'road', translation_es: 'camino', translation_sv: 'väg', difficulty: 'easy', category: 'noun' },
  { word: 'MAA', translation: 'land', translation_es: 'tierra', translation_sv: 'land', difficulty: 'easy', category: 'noun' },
  { word: 'YÖ', translation: 'night', translation_es: 'noche', translation_sv: 'natt', difficulty: 'easy', category: 'noun' },
  { word: 'JÄÄ', translation: 'ice', translation_es: 'hielo', translation_sv: 'is', difficulty: 'easy', category: 'noun' },
  { word: 'KALA', translation: 'fish', translation_es: 'pez', translation_sv: 'fisk', difficulty: 'easy', category: 'noun' },
  { word: 'SIKA', translation: 'pig', translation_es: 'cerdo', translation_sv: 'gris', difficulty: 'easy', category: 'noun' },
  { word: 'KANA', translation: 'chicken', translation_es: 'pollo', translation_sv: 'kyckling', difficulty: 'easy', category: 'noun' },
  { word: 'HEVONEN', translation: 'horse', translation_es: 'caballo', translation_sv: 'häst', difficulty: 'easy', category: 'noun' },
  { word: 'KUKKA', translation: 'flower', translation_es: 'flor', translation_sv: 'blomma', difficulty: 'easy', category: 'noun' },
  { word: 'VESI', translation: 'water', translation_es: 'agua', translation_sv: 'vatten', difficulty: 'easy', category: 'noun' },
  { word: 'TULI', translation: 'fire', translation_es: 'fuego', translation_sv: 'eld', difficulty: 'easy', category: 'noun' },
  { word: 'LUMI', translation: 'snow', translation_es: 'nieve', translation_sv: 'snö', difficulty: 'easy', category: 'noun' },
  { word: 'TUULI', translation: 'wind', translation_es: 'viento', translation_sv: 'vind', difficulty: 'easy', category: 'noun' },
  { word: 'OVI', translation: 'door', translation_es: 'puerta', translation_sv: 'dörr', difficulty: 'easy', category: 'noun' },
  { word: 'ISÄ', translation: 'father', translation_es: 'padre', translation_sv: 'pappa', difficulty: 'easy', category: 'noun' },
  { word: 'ÄITI', translation: 'mother', translation_es: 'madre', translation_sv: 'mamma', difficulty: 'easy', category: 'noun' },
  { word: 'SUSI', translation: 'wolf', translation_es: 'lobo', translation_sv: 'varg', difficulty: 'easy', category: 'noun' },
  { word: 'HIIRI', translation: 'mouse', translation_es: 'ratón', translation_sv: 'mus', difficulty: 'easy', category: 'noun' },
  { word: 'PÖYTÄ', translation: 'table', translation_es: 'mesa', translation_sv: 'bord', difficulty: 'easy', category: 'noun' },
  { word: 'TUOLI', translation: 'chair', translation_es: 'silla', translation_sv: 'stol', difficulty: 'easy', category: 'noun' },
  { word: 'KIRJA', translation: 'book', translation_es: 'libro', translation_sv: 'bok', difficulty: 'easy', category: 'noun' },
  { word: 'PALLO', translation: 'ball', translation_es: 'pelota', translation_sv: 'boll', difficulty: 'easy', category: 'noun' },
  { word: 'AURINKO', translation: 'sun', translation_es: 'sol', translation_sv: 'sol', difficulty: 'easy', category: 'noun' },
  { word: 'KUU', translation: 'moon', translation_es: 'luna', translation_sv: 'måne', difficulty: 'easy', category: 'noun' },
  { word: 'SILMÄ', translation: 'eye', translation_es: 'ojo', translation_sv: 'öga', difficulty: 'easy', category: 'noun' },
  { word: 'KÄSI', translation: 'hand', translation_es: 'mano', translation_sv: 'hand', difficulty: 'easy', category: 'noun' },
  { word: 'JALKA', translation: 'foot', translation_es: 'pie', translation_sv: 'fot', difficulty: 'easy', category: 'noun' },
  { word: 'NENÄ', translation: 'nose', translation_es: 'nariz', translation_sv: 'näsa', difficulty: 'easy', category: 'noun' },
  { word: 'KORVA', translation: 'ear', translation_es: 'oreja', translation_sv: 'öra', difficulty: 'easy', category: 'noun' },
  { word: 'SÄNKY', translation: 'bed', translation_es: 'cama', translation_sv: 'säng', difficulty: 'easy', category: 'noun' },
  { word: 'HATTU', translation: 'hat', translation_es: 'sombrero', translation_sv: 'hatt', difficulty: 'easy', category: 'noun' },
  { word: 'SUKKA', translation: 'sock', translation_es: 'calcetín', translation_sv: 'strumpa', difficulty: 'easy', category: 'noun' },
  { word: 'MUNA', translation: 'egg', translation_es: 'huevo', translation_sv: 'ägg', difficulty: 'easy', category: 'noun' },
  { word: 'JUUSTO', translation: 'cheese', translation_es: 'queso', translation_sv: 'ost', difficulty: 'easy', category: 'noun' },
  { word: 'PÄÄ', translation: 'head', translation_es: 'cabeza', translation_sv: 'huvud', difficulty: 'easy', category: 'noun' },
  { word: 'VATSA', translation: 'stomach', translation_es: 'estómago', translation_sv: 'mage', difficulty: 'easy', category: 'noun' },
  { word: 'SADE', translation: 'rain', translation_es: 'lluvia', translation_sv: 'regn', difficulty: 'easy', category: 'noun' },
  { word: 'PILVI', translation: 'cloud', translation_es: 'nube', translation_sv: 'moln', difficulty: 'easy', category: 'noun' },
  { word: 'TÄHTI', translation: 'star', translation_es: 'estrella', translation_sv: 'stjärna', difficulty: 'easy', category: 'noun' },
  { word: 'MERI', translation: 'sea', translation_es: 'mar', translation_sv: 'hav', difficulty: 'easy', category: 'noun' },
  { word: 'JÄRVI', translation: 'lake', translation_es: 'lago', translation_sv: 'sjö', difficulty: 'easy', category: 'noun' },
  { word: 'JOKI', translation: 'river', translation_es: 'río', translation_sv: 'flod', difficulty: 'easy', category: 'noun' },
  { word: 'KIVI', translation: 'stone', translation_es: 'piedra', translation_sv: 'sten', difficulty: 'easy', category: 'noun' },
  { word: 'LEHTI', translation: 'leaf', translation_es: 'hoja', translation_sv: 'löv', difficulty: 'easy', category: 'noun' },
  { word: 'RUOKA', translation: 'food', translation_es: 'comida', translation_sv: 'mat', difficulty: 'easy', category: 'noun' },
  { word: 'JUOMA', translation: 'drink', translation_es: 'bebida', translation_sv: 'dryck', difficulty: 'easy', category: 'noun' },
  { word: 'LAPSI', translation: 'child', translation_es: 'niño', translation_sv: 'barn', difficulty: 'easy', category: 'noun' },
  { word: 'POIKA', translation: 'boy', translation_es: 'chico', translation_sv: 'pojke', difficulty: 'easy', category: 'noun' },
  { word: 'TYTTÖ', translation: 'girl', translation_es: 'chica', translation_sv: 'flicka', difficulty: 'easy', category: 'noun' },
  { word: 'MIES', translation: 'man', translation_es: 'hombre', translation_sv: 'man', difficulty: 'easy', category: 'noun' },
  { word: 'NAINEN', translation: 'woman', translation_es: 'mujer', translation_sv: 'kvinna', difficulty: 'easy', category: 'noun' },
  { word: 'VALO', translation: 'light', translation_es: 'luz', translation_sv: 'ljus', difficulty: 'easy', category: 'noun' },
  { word: 'ÄÄNI', translation: 'sound', translation_es: 'sonido', translation_sv: 'ljud', difficulty: 'easy', category: 'noun' },
  { word: 'KOTI', translation: 'home', translation_es: 'hogar', translation_sv: 'hem', difficulty: 'easy', category: 'noun' },
  { word: 'LELU', translation: 'toy', translation_es: 'juguete', translation_sv: 'leksak', difficulty: 'easy', category: 'noun' },
  { word: 'PELI', translation: 'game', translation_es: 'juego', translation_sv: 'spel', difficulty: 'easy', category: 'noun' },
  { word: 'VAUVAA', translation: 'baby', translation_es: 'bebé', translation_sv: 'bebis', difficulty: 'easy', category: 'noun' },
  { word: 'LINTU', translation: 'bird', translation_es: 'pájaro', translation_sv: 'fågel', difficulty: 'easy', category: 'noun' },
  { word: 'RUOHO', translation: 'grass', translation_es: 'hierba', translation_sv: 'gräs', difficulty: 'easy', category: 'noun' },
  { word: 'HIEKKA', translation: 'sand', translation_es: 'arena', translation_sv: 'sand', difficulty: 'easy', category: 'noun' },
  { word: 'LASI', translation: 'glass', translation_es: 'vaso', translation_sv: 'glas', difficulty: 'easy', category: 'noun' },
  { word: 'KUPPI', translation: 'cup', translation_es: 'taza', translation_sv: 'kopp', difficulty: 'easy', category: 'noun' },
  { word: 'LUSIKKA', translation: 'spoon', translation_es: 'cuchara', translation_sv: 'sked', difficulty: 'easy', category: 'noun' },
  { word: 'VEITSI', translation: 'knife', translation_es: 'cuchillo', translation_sv: 'kniv', difficulty: 'easy', category: 'noun' },

  // --- Medium nouns (~70) ---
  { word: 'KYNÄ', translation: 'pen', translation_es: 'bolígrafo', translation_sv: 'penna', difficulty: 'medium', category: 'noun' },
  { word: 'KOULU', translation: 'school', translation_es: 'escuela', translation_sv: 'skola', difficulty: 'medium', category: 'noun' },
  { word: 'PUISTO', translation: 'park', translation_es: 'parque', translation_sv: 'park', difficulty: 'medium', category: 'noun' },
  { word: 'KAUPPA', translation: 'shop', translation_es: 'tienda', translation_sv: 'affär', difficulty: 'medium', category: 'noun' },
  { word: 'LEIPÄ', translation: 'bread', translation_es: 'pan', translation_sv: 'bröd', difficulty: 'medium', category: 'noun' },
  { word: 'MAITO', translation: 'milk', translation_es: 'leche', translation_sv: 'mjölk', difficulty: 'medium', category: 'noun' },
  { word: 'OMENA', translation: 'apple', translation_es: 'manzana', translation_sv: 'äpple', difficulty: 'medium', category: 'noun' },
  { word: 'BANAANI', translation: 'banana', translation_es: 'plátano', translation_sv: 'banan', difficulty: 'medium', category: 'noun' },
  { word: 'MANSIKKA', translation: 'strawberry', translation_es: 'fresa', translation_sv: 'jordgubbe', difficulty: 'medium', category: 'noun' },
  { word: 'PORKKANA', translation: 'carrot', translation_es: 'zanahoria', translation_sv: 'morot', difficulty: 'medium', category: 'noun' },
  { word: 'PERUNA', translation: 'potato', translation_es: 'patata', translation_sv: 'potatis', difficulty: 'medium', category: 'noun' },
  { word: 'SORMI', translation: 'finger', translation_es: 'dedo', translation_sv: 'finger', difficulty: 'medium', category: 'noun' },
  { word: 'POLVI', translation: 'knee', translation_es: 'rodilla', translation_sv: 'knä', difficulty: 'medium', category: 'noun' },
  { word: 'OLKAPÄÄ', translation: 'shoulder', translation_es: 'hombro', translation_sv: 'axel', difficulty: 'medium', category: 'noun' },
  { word: 'HAMMAS', translation: 'tooth', translation_es: 'diente', translation_sv: 'tand', difficulty: 'medium', category: 'noun' },
  { word: 'KENKÄ', translation: 'shoe', translation_es: 'zapato', translation_sv: 'sko', difficulty: 'medium', category: 'noun' },
  { word: 'TAKKI', translation: 'coat', translation_es: 'abrigo', translation_sv: 'kappa', difficulty: 'medium', category: 'noun' },
  { word: 'HOUSUT', translation: 'pants', translation_es: 'pantalones', translation_sv: 'byxor', difficulty: 'medium', category: 'noun' },
  { word: 'PAITA', translation: 'shirt', translation_es: 'camisa', translation_sv: 'skjorta', difficulty: 'medium', category: 'noun' },
  { word: 'MEKKO', translation: 'dress', translation_es: 'vestido', translation_sv: 'klänning', difficulty: 'medium', category: 'noun' },
  { word: 'KARHU', translation: 'bear', translation_es: 'oso', translation_sv: 'björn', difficulty: 'medium', category: 'noun' },
  { word: 'KETTU', translation: 'fox', translation_es: 'zorro', translation_sv: 'räv', difficulty: 'medium', category: 'noun' },
  { word: 'JÄNIS', translation: 'rabbit', translation_es: 'conejo', translation_sv: 'kanin', difficulty: 'medium', category: 'noun' },
  { word: 'NORSU', translation: 'elephant', translation_es: 'elefante', translation_sv: 'elefant', difficulty: 'medium', category: 'noun' },
  { word: 'LEIJONA', translation: 'lion', translation_es: 'león', translation_sv: 'lejon', difficulty: 'medium', category: 'noun' },
  { word: 'TIIKERI', translation: 'tiger', translation_es: 'tigre', translation_sv: 'tiger', difficulty: 'medium', category: 'noun' },
  { word: 'SAMMAKKO', translation: 'frog', translation_es: 'rana', translation_sv: 'groda', difficulty: 'medium', category: 'noun' },
  { word: 'KILPIKONNA', translation: 'turtle', translation_es: 'tortuga', translation_sv: 'sköldpadda', difficulty: 'medium', category: 'noun' },
  { word: 'SATEENVARJO', translation: 'umbrella', translation_es: 'paraguas', translation_sv: 'paraply', difficulty: 'medium', category: 'noun' },
  { word: 'PYÖRÄ', translation: 'bicycle', translation_es: 'bicicleta', translation_sv: 'cykel', difficulty: 'medium', category: 'noun' },
  { word: 'LAIVA', translation: 'ship', translation_es: 'barco', translation_sv: 'skepp', difficulty: 'medium', category: 'noun' },
  { word: 'JUNA', translation: 'train', translation_es: 'tren', translation_sv: 'tåg', difficulty: 'medium', category: 'noun' },
  { word: 'BUSSI', translation: 'bus', translation_es: 'autobús', translation_sv: 'buss', difficulty: 'medium', category: 'noun' },
  { word: 'PUHELIN', translation: 'phone', translation_es: 'teléfono', translation_sv: 'telefon', difficulty: 'medium', category: 'noun' },
  { word: 'KELLO', translation: 'clock', translation_es: 'reloj', translation_sv: 'klocka', difficulty: 'medium', category: 'noun' },
  { word: 'AVAIN', translation: 'key', translation_es: 'llave', translation_sv: 'nyckel', difficulty: 'medium', category: 'noun' },
  { word: 'LAMPPU', translation: 'lamp', translation_es: 'lámpara', translation_sv: 'lampa', difficulty: 'medium', category: 'noun' },
  { word: 'PEILI', translation: 'mirror', translation_es: 'espejo', translation_sv: 'spegel', difficulty: 'medium', category: 'noun' },
  { word: 'KUKKARO', translation: 'wallet', translation_es: 'cartera', translation_sv: 'plånbok', difficulty: 'medium', category: 'noun' },
  { word: 'REPPU', translation: 'backpack', translation_es: 'mochila', translation_sv: 'ryggsäck', difficulty: 'medium', category: 'noun' },
  { word: 'SIENI', translation: 'mushroom', translation_es: 'seta', translation_sv: 'svamp', difficulty: 'medium', category: 'noun' },
  { word: 'MARJA', translation: 'berry', translation_es: 'baya', translation_sv: 'bär', difficulty: 'medium', category: 'noun' },
  { word: 'PÄÄRYNÄ', translation: 'pear', translation_es: 'pera', translation_sv: 'päron', difficulty: 'medium', category: 'noun' },
  { word: 'KIRSIKKA', translation: 'cherry', translation_es: 'cereza', translation_sv: 'körsbär', difficulty: 'medium', category: 'noun' },
  { word: 'SIPULI', translation: 'onion', translation_es: 'cebolla', translation_sv: 'lök', difficulty: 'medium', category: 'noun' },
  { word: 'TOMAATTI', translation: 'tomato', translation_es: 'tomate', translation_sv: 'tomat', difficulty: 'medium', category: 'noun' },
  { word: 'KURKKU', translation: 'cucumber', translation_es: 'pepino', translation_sv: 'gurka', difficulty: 'medium', category: 'noun' },
  { word: 'SALAATTI', translation: 'salad', translation_es: 'ensalada', translation_sv: 'sallad', difficulty: 'medium', category: 'noun' },
  { word: 'KANELI', translation: 'cinnamon', translation_es: 'canela', translation_sv: 'kanel', difficulty: 'medium', category: 'noun' },
  { word: 'SOKERI', translation: 'sugar', translation_es: 'azúcar', translation_sv: 'socker', difficulty: 'medium', category: 'noun' },
  { word: 'SUOLA', translation: 'salt', translation_es: 'sal', translation_sv: 'salt', difficulty: 'medium', category: 'noun' },
  { word: 'PIPPURI', translation: 'pepper', translation_es: 'pimienta', translation_sv: 'peppar', difficulty: 'medium', category: 'noun' },
  { word: 'KAMERA', translation: 'camera', translation_es: 'cámara', translation_sv: 'kamera', difficulty: 'medium', category: 'noun' },
  { word: 'RADIO', translation: 'radio', translation_es: 'radio', translation_sv: 'radio', difficulty: 'medium', category: 'noun' },
  { word: 'SANOMALEHTI', translation: 'newspaper', translation_es: 'periódico', translation_sv: 'tidning', difficulty: 'medium', category: 'noun' },
  { word: 'POSTIKORTTI', translation: 'postcard', translation_es: 'postal', translation_sv: 'vykort', difficulty: 'medium', category: 'noun' },
  { word: 'SILTA', translation: 'bridge', translation_es: 'puente', translation_sv: 'bro', difficulty: 'medium', category: 'noun' },
  { word: 'TORNI', translation: 'tower', translation_es: 'torre', translation_sv: 'torn', difficulty: 'medium', category: 'noun' },
  { word: 'SAARI', translation: 'island', translation_es: 'isla', translation_sv: 'ö', difficulty: 'medium', category: 'noun' },
  { word: 'VUORI', translation: 'mountain', translation_es: 'montaña', translation_sv: 'berg', difficulty: 'medium', category: 'noun' },
  { word: 'METSÄ', translation: 'forest', translation_es: 'bosque', translation_sv: 'skog', difficulty: 'medium', category: 'noun' },
  { word: 'NIITTY', translation: 'meadow', translation_es: 'prado', translation_sv: 'äng', difficulty: 'medium', category: 'noun' },
  { word: 'RANTA', translation: 'beach', translation_es: 'playa', translation_sv: 'strand', difficulty: 'medium', category: 'noun' },
  { word: 'SATAMA', translation: 'harbor', translation_es: 'puerto', translation_sv: 'hamn', difficulty: 'medium', category: 'noun' },
  { word: 'ASEMA', translation: 'station', translation_es: 'estación', translation_sv: 'station', difficulty: 'medium', category: 'noun' },
  { word: 'KIRKKO', translation: 'church', translation_es: 'iglesia', translation_sv: 'kyrka', difficulty: 'medium', category: 'noun' },
  { word: 'MUSEO', translation: 'museum', translation_es: 'museo', translation_sv: 'museum', difficulty: 'medium', category: 'noun' },
  { word: 'TEATTERI', translation: 'theater', translation_es: 'teatro', translation_sv: 'teater', difficulty: 'medium', category: 'noun' },
  { word: 'STADION', translation: 'stadium', translation_es: 'estadio', translation_sv: 'stadion', difficulty: 'medium', category: 'noun' },
  { word: 'LENTOKONE', translation: 'airplane', translation_es: 'avión', translation_sv: 'flygplan', difficulty: 'medium', category: 'noun' },

  // --- Hard nouns (~70) ---
  { word: 'PERHONEN', translation: 'butterfly', translation_es: 'mariposa', translation_sv: 'fjäril', difficulty: 'hard', category: 'noun' },
  { word: 'KIRJASTO', translation: 'library', translation_es: 'biblioteca', translation_sv: 'bibliotek', difficulty: 'hard', category: 'noun' },
  { word: 'JÄÄKARHU', translation: 'polar bear', translation_es: 'oso polar', translation_sv: 'isbjörn', difficulty: 'hard', category: 'noun' },
  { word: 'DINOSAURUS', translation: 'dinosaur', translation_es: 'dinosaurio', translation_sv: 'dinosaurie', difficulty: 'hard', category: 'noun' },
  { word: 'SAIRAALA', translation: 'hospital', translation_es: 'hospital', translation_sv: 'sjukhus', difficulty: 'hard', category: 'noun' },
  { word: 'RAVINTOLA', translation: 'restaurant', translation_es: 'restaurante', translation_sv: 'restaurang', difficulty: 'hard', category: 'noun' },
  { word: 'APPELSIINI', translation: 'orange', translation_es: 'naranja', translation_sv: 'apelsin', difficulty: 'hard', category: 'noun' },
  { word: 'SUKLAA', translation: 'chocolate', translation_es: 'chocolate', translation_sv: 'choklad', difficulty: 'hard', category: 'noun' },
  { word: 'JÄÄTELÖ', translation: 'ice cream', translation_es: 'helado', translation_sv: 'glass', difficulty: 'hard', category: 'noun' },
  { word: 'LUMIUKKO', translation: 'snowman', translation_es: 'muñeco de nieve', translation_sv: 'snögubbe', difficulty: 'hard', category: 'noun' },
  { word: 'TIETOKONE', translation: 'computer', translation_es: 'ordenador', translation_sv: 'dator', difficulty: 'hard', category: 'noun' },
  { word: 'TELEVISIO', translation: 'television', translation_es: 'televisión', translation_sv: 'television', difficulty: 'hard', category: 'noun' },
  { word: 'HELIKOPTERI', translation: 'helicopter', translation_es: 'helicóptero', translation_sv: 'helikopter', difficulty: 'hard', category: 'noun' },
  { word: 'LIIKENNEVALO', translation: 'traffic light', translation_es: 'semáforo', translation_sv: 'trafikljus', difficulty: 'hard', category: 'noun' },
  { word: 'MUURAHAINEN', translation: 'ant', translation_es: 'hormiga', translation_sv: 'myra', difficulty: 'hard', category: 'noun' },
  { word: 'ELEFANTTI', translation: 'elephant', translation_es: 'elefante', translation_sv: 'elefant', difficulty: 'hard', category: 'noun' },
  { word: 'KROKOTIILI', translation: 'crocodile', translation_es: 'cocodrilo', translation_sv: 'krokodil', difficulty: 'hard', category: 'noun' },
  { word: 'VIRTAHEPO', translation: 'hippo', translation_es: 'hipopótamo', translation_sv: 'flodhäst', difficulty: 'hard', category: 'noun' },
  { word: 'SÄHKÖJUNA', translation: 'electric train', translation_es: 'tren eléctrico', translation_sv: 'eltåg', difficulty: 'hard', category: 'noun' },
  { word: 'PALOAUTO', translation: 'fire truck', translation_es: 'camión de bomberos', translation_sv: 'brandbil', difficulty: 'hard', category: 'noun' },
  { word: 'AMBULANSSI', translation: 'ambulance', translation_es: 'ambulancia', translation_sv: 'ambulans', difficulty: 'hard', category: 'noun' },
  { word: 'LASTENTARHA', translation: 'kindergarten', translation_es: 'jardín de infancia', translation_sv: 'förskola', difficulty: 'hard', category: 'noun' },
  { word: 'UIMAHALLI', translation: 'swimming pool', translation_es: 'piscina', translation_sv: 'simhall', difficulty: 'hard', category: 'noun' },
  { word: 'HUVIPUISTO', translation: 'amusement park', translation_es: 'parque de atracciones', translation_sv: 'nöjespark', difficulty: 'hard', category: 'noun' },
  { word: 'VUORISTORATA', translation: 'roller coaster', translation_es: 'montaña rusa', translation_sv: 'berg-och-dalbana', difficulty: 'hard', category: 'noun' },
  { word: 'HAMMASHARJA', translation: 'toothbrush', translation_es: 'cepillo de dientes', translation_sv: 'tandborste', difficulty: 'hard', category: 'noun' },
  { word: 'AURINGONKUKKA', translation: 'sunflower', translation_es: 'girasol', translation_sv: 'solros', difficulty: 'hard', category: 'noun' },
  { word: 'VESIPUTOUS', translation: 'waterfall', translation_es: 'cascada', translation_sv: 'vattenfall', difficulty: 'hard', category: 'noun' },
  { word: 'LENTOKENTTÄ', translation: 'airport', translation_es: 'aeropuerto', translation_sv: 'flygplats', difficulty: 'hard', category: 'noun' },
  { word: 'YLIOPISTO', translation: 'university', translation_es: 'universidad', translation_sv: 'universitet', difficulty: 'hard', category: 'noun' },
  { word: 'KAMPAAMO', translation: 'hairdresser', translation_es: 'peluquería', translation_sv: 'frisör', difficulty: 'hard', category: 'noun' },
  { word: 'LEIPOMO', translation: 'bakery', translation_es: 'panadería', translation_sv: 'bageri', difficulty: 'hard', category: 'noun' },
  { word: 'APTEEKKI', translation: 'pharmacy', translation_es: 'farmacia', translation_sv: 'apotek', difficulty: 'hard', category: 'noun' },
  { word: 'PÄÄMINISTERI', translation: 'prime minister', translation_es: 'primer ministro', translation_sv: 'statsminister', difficulty: 'hard', category: 'noun' },
  { word: 'PRESIDENTTI', translation: 'president', translation_es: 'presidente', translation_sv: 'president', difficulty: 'hard', category: 'noun' },
  { word: 'HARRASTUS', translation: 'hobby', translation_es: 'afición', translation_sv: 'hobby', difficulty: 'hard', category: 'noun' },
  { word: 'JOUKKUE', translation: 'team', translation_es: 'equipo', translation_sv: 'lag', difficulty: 'hard', category: 'noun' },
  { word: 'KILPAILU', translation: 'competition', translation_es: 'competición', translation_sv: 'tävling', difficulty: 'hard', category: 'noun' },
  { word: 'JÄÄKAAPPI', translation: 'refrigerator', translation_es: 'refrigerador', translation_sv: 'kylskåp', difficulty: 'hard', category: 'noun' },
  { word: 'PESUKONE', translation: 'washing machine', translation_es: 'lavadora', translation_sv: 'tvättmaskin', difficulty: 'hard', category: 'noun' },
  { word: 'ASTIANPESUKONE', translation: 'dishwasher', translation_es: 'lavavajillas', translation_sv: 'diskmaskin', difficulty: 'hard', category: 'noun' },
  { word: 'PÖLYNIMURI', translation: 'vacuum cleaner', translation_es: 'aspiradora', translation_sv: 'dammsugare', difficulty: 'hard', category: 'noun' },
  { word: 'SÄHKÖPOSTI', translation: 'email', translation_es: 'correo electrónico', translation_sv: 'e-post', difficulty: 'hard', category: 'noun' },
  { word: 'MATKAPUHELIN', translation: 'mobile phone', translation_es: 'teléfono móvil', translation_sv: 'mobiltelefon', difficulty: 'hard', category: 'noun' },
  { word: 'VALOKUVA', translation: 'photograph', translation_es: 'fotografía', translation_sv: 'fotografi', difficulty: 'hard', category: 'noun' },
  { word: 'MAISEMA', translation: 'landscape', translation_es: 'paisaje', translation_sv: 'landskap', difficulty: 'hard', category: 'noun' },
  { word: 'SADEMETSÄ', translation: 'rainforest', translation_es: 'selva tropical', translation_sv: 'regnskog', difficulty: 'hard', category: 'noun' },
  { word: 'TULIVUORI', translation: 'volcano', translation_es: 'volcán', translation_sv: 'vulkan', difficulty: 'hard', category: 'noun' },
  { word: 'MAANJÄRISTYS', translation: 'earthquake', translation_es: 'terremoto', translation_sv: 'jordbävning', difficulty: 'hard', category: 'noun' },
  { word: 'REVONTULET', translation: 'northern lights', translation_es: 'aurora boreal', translation_sv: 'norrsken', difficulty: 'hard', category: 'noun' },
  { word: 'SATEENKAARI', translation: 'rainbow', translation_es: 'arcoíris', translation_sv: 'regnbåge', difficulty: 'hard', category: 'noun' },
  { word: 'LUMIMYRSKY', translation: 'snowstorm', translation_es: 'tormenta de nieve', translation_sv: 'snöstorm', difficulty: 'hard', category: 'noun' },
  { word: 'HYÖNTEINEN', translation: 'insect', translation_es: 'insecto', translation_sv: 'insekt', difficulty: 'hard', category: 'noun' },
  { word: 'LEPPÄKERTTU', translation: 'ladybug', translation_es: 'mariquita', translation_sv: 'nyckelpiga', difficulty: 'hard', category: 'noun' },
  { word: 'SUDENKORENTO', translation: 'dragonfly', translation_es: 'libélula', translation_sv: 'trollslända', difficulty: 'hard', category: 'noun' },
  { word: 'MEHILÄINEN', translation: 'bee', translation_es: 'abeja', translation_sv: 'bi', difficulty: 'hard', category: 'noun' },
  { word: 'HÄMÄHÄKKI', translation: 'spider', translation_es: 'araña', translation_sv: 'spindel', difficulty: 'hard', category: 'noun' },
  { word: 'ETANA', translation: 'snail', translation_es: 'caracol', translation_sv: 'snigel', difficulty: 'hard', category: 'noun' },
  { word: 'MUSTEKALA', translation: 'octopus', translation_es: 'pulpo', translation_sv: 'bläckfisk', difficulty: 'hard', category: 'noun' },
  { word: 'MERITÄHTI', translation: 'starfish', translation_es: 'estrella de mar', translation_sv: 'sjöstjärna', difficulty: 'hard', category: 'noun' },
  { word: 'MEDUUSA', translation: 'jellyfish', translation_es: 'medusa', translation_sv: 'manet', difficulty: 'hard', category: 'noun' },
  { word: 'MIELIKUVITUS', translation: 'imagination', translation_es: 'imaginación', translation_sv: 'fantasi', difficulty: 'hard', category: 'noun' },
  { word: 'SEIKKAILU', translation: 'adventure', translation_es: 'aventura', translation_sv: 'äventyr', difficulty: 'hard', category: 'noun' },
  { word: 'YSTÄVYYS', translation: 'friendship', translation_es: 'amistad', translation_sv: 'vänskap', difficulty: 'hard', category: 'noun' },
  { word: 'ROHKEUS', translation: 'courage', translation_es: 'valentía', translation_sv: 'mod', difficulty: 'hard', category: 'noun' },
  { word: 'ONNI', translation: 'happiness', translation_es: 'felicidad', translation_sv: 'lycka', difficulty: 'hard', category: 'noun' },

  // ============================================================
  // VERBS (infinitive/dictionary form)
  // ============================================================

  // --- Easy verbs (~50) ---
  { word: 'OLLA', translation: 'to be', translation_es: 'ser', translation_sv: 'att vara', difficulty: 'easy', category: 'verb' },
  { word: 'MENNÄ', translation: 'to go', translation_es: 'ir', translation_sv: 'att gå', difficulty: 'easy', category: 'verb' },
  { word: 'TULLA', translation: 'to come', translation_es: 'venir', translation_sv: 'att komma', difficulty: 'easy', category: 'verb' },
  { word: 'SYÖDÄ', translation: 'to eat', translation_es: 'comer', translation_sv: 'att äta', difficulty: 'easy', category: 'verb' },
  { word: 'JUODA', translation: 'to drink', translation_es: 'beber', translation_sv: 'att dricka', difficulty: 'easy', category: 'verb' },
  { word: 'LUKEA', translation: 'to read', translation_es: 'leer', translation_sv: 'att läsa', difficulty: 'easy', category: 'verb' },
  { word: 'NÄHDÄ', translation: 'to see', translation_es: 'ver', translation_sv: 'att se', difficulty: 'easy', category: 'verb' },
  { word: 'KUULLA', translation: 'to hear', translation_es: 'oír', translation_sv: 'att höra', difficulty: 'easy', category: 'verb' },
  { word: 'PUHUA', translation: 'to speak', translation_es: 'hablar', translation_sv: 'att tala', difficulty: 'easy', category: 'verb' },
  { word: 'SANOA', translation: 'to say', translation_es: 'decir', translation_sv: 'att säga', difficulty: 'easy', category: 'verb' },
  { word: 'TEHDÄ', translation: 'to do', translation_es: 'hacer', translation_sv: 'att göra', difficulty: 'easy', category: 'verb' },
  { word: 'OTTAA', translation: 'to take', translation_es: 'tomar', translation_sv: 'att ta', difficulty: 'easy', category: 'verb' },
  { word: 'ANTAA', translation: 'to give', translation_es: 'dar', translation_sv: 'att ge', difficulty: 'easy', category: 'verb' },
  { word: 'ISTUA', translation: 'to sit', translation_es: 'sentarse', translation_sv: 'att sitta', difficulty: 'easy', category: 'verb' },
  { word: 'NOUSTA', translation: 'to rise', translation_es: 'levantarse', translation_sv: 'att stiga', difficulty: 'easy', category: 'verb' },
  { word: 'KÄVELLÄ', translation: 'to walk', translation_es: 'caminar', translation_sv: 'att gå', difficulty: 'easy', category: 'verb' },
  { word: 'JUOSTA', translation: 'to run', translation_es: 'correr', translation_sv: 'att springa', difficulty: 'easy', category: 'verb' },
  { word: 'HYPÄTÄ', translation: 'to jump', translation_es: 'saltar', translation_sv: 'att hoppa', difficulty: 'easy', category: 'verb' },
  { word: 'UIDA', translation: 'to swim', translation_es: 'nadar', translation_sv: 'att simma', difficulty: 'easy', category: 'verb' },
  { word: 'LENTÄÄ', translation: 'to fly', translation_es: 'volar', translation_sv: 'att flyga', difficulty: 'easy', category: 'verb' },
  { word: 'NUKKUA', translation: 'to sleep', translation_es: 'dormir', translation_sv: 'att sova', difficulty: 'easy', category: 'verb' },
  { word: 'HERÄTÄ', translation: 'to wake up', translation_es: 'despertarse', translation_sv: 'att vakna', difficulty: 'easy', category: 'verb' },
  { word: 'ITKEÄ', translation: 'to cry', translation_es: 'llorar', translation_sv: 'att gråta', difficulty: 'easy', category: 'verb' },
  { word: 'NAURAA', translation: 'to laugh', translation_es: 'reír', translation_sv: 'att skratta', difficulty: 'easy', category: 'verb' },
  { word: 'LEIKKIÄ', translation: 'to play', translation_es: 'jugar', translation_sv: 'att leka', difficulty: 'easy', category: 'verb' },
  { word: 'LAULAA', translation: 'to sing', translation_es: 'cantar', translation_sv: 'att sjunga', difficulty: 'easy', category: 'verb' },
  { word: 'TANSSIA', translation: 'to dance', translation_es: 'bailar', translation_sv: 'att dansa', difficulty: 'easy', category: 'verb' },
  { word: 'PIIRTÄÄ', translation: 'to draw', translation_es: 'dibujar', translation_sv: 'att rita', difficulty: 'easy', category: 'verb' },
  { word: 'KIRJOITTAA', translation: 'to write', translation_es: 'escribir', translation_sv: 'att skriva', difficulty: 'easy', category: 'verb' },
  { word: 'AVATA', translation: 'to open', translation_es: 'abrir', translation_sv: 'att öppna', difficulty: 'easy', category: 'verb' },
  { word: 'SULKEA', translation: 'to close', translation_es: 'cerrar', translation_sv: 'att stänga', difficulty: 'easy', category: 'verb' },
  { word: 'PESTÄ', translation: 'to wash', translation_es: 'lavar', translation_sv: 'att tvätta', difficulty: 'easy', category: 'verb' },
  { word: 'AUTTAA', translation: 'to help', translation_es: 'ayudar', translation_sv: 'att hjälpa', difficulty: 'easy', category: 'verb' },
  { word: 'ODOTTAA', translation: 'to wait', translation_es: 'esperar', translation_sv: 'att vänta', difficulty: 'easy', category: 'verb' },
  { word: 'ETSIÄ', translation: 'to search', translation_es: 'buscar', translation_sv: 'att söka', difficulty: 'easy', category: 'verb' },
  { word: 'LÖYTÄÄ', translation: 'to find', translation_es: 'encontrar', translation_sv: 'att hitta', difficulty: 'easy', category: 'verb' },
  { word: 'PITÄÄ', translation: 'to like', translation_es: 'gustar', translation_sv: 'att tycka om', difficulty: 'easy', category: 'verb' },
  { word: 'HALUTA', translation: 'to want', translation_es: 'querer', translation_sv: 'att vilja', difficulty: 'easy', category: 'verb' },
  { word: 'OSATA', translation: 'to know how', translation_es: 'saber', translation_sv: 'att kunna', difficulty: 'easy', category: 'verb' },
  { word: 'VOIDA', translation: 'to be able', translation_es: 'poder', translation_sv: 'att kunna', difficulty: 'easy', category: 'verb' },
  { word: 'TIETÄÄ', translation: 'to know', translation_es: 'saber', translation_sv: 'att veta', difficulty: 'easy', category: 'verb' },
  { word: 'PELATA', translation: 'to play', translation_es: 'jugar', translation_sv: 'att spela', difficulty: 'easy', category: 'verb' },
  { word: 'ASUA', translation: 'to live', translation_es: 'vivir', translation_sv: 'att bo', difficulty: 'easy', category: 'verb' },
  { word: 'RAKASTAA', translation: 'to love', translation_es: 'amar', translation_sv: 'att älska', difficulty: 'easy', category: 'verb' },
  { word: 'OPPIA', translation: 'to learn', translation_es: 'aprender', translation_sv: 'att lära sig', difficulty: 'easy', category: 'verb' },
  { word: 'SEISOA', translation: 'to stand', translation_es: 'estar de pie', translation_sv: 'att stå', difficulty: 'easy', category: 'verb' },
  { word: 'PUDOTA', translation: 'to fall', translation_es: 'caer', translation_sv: 'att falla', difficulty: 'easy', category: 'verb' },
  { word: 'KANTAA', translation: 'to carry', translation_es: 'llevar', translation_sv: 'att bära', difficulty: 'easy', category: 'verb' },
  { word: 'HEITTÄÄ', translation: 'to throw', translation_es: 'lanzar', translation_sv: 'att kasta', difficulty: 'easy', category: 'verb' },
  { word: 'KATSOA', translation: 'to watch', translation_es: 'mirar', translation_sv: 'att titta', difficulty: 'easy', category: 'verb' },

  // --- Medium verbs (~50) ---
  { word: 'AJATELLA', translation: 'to think', translation_es: 'pensar', translation_sv: 'att tänka', difficulty: 'medium', category: 'verb' },
  { word: 'MUISTAA', translation: 'to remember', translation_es: 'recordar', translation_sv: 'att minnas', difficulty: 'medium', category: 'verb' },
  { word: 'UNOHTAA', translation: 'to forget', translation_es: 'olvidar', translation_sv: 'att glömma', difficulty: 'medium', category: 'verb' },
  { word: 'YMMÄRTÄÄ', translation: 'to understand', translation_es: 'entender', translation_sv: 'att förstå', difficulty: 'medium', category: 'verb' },
  { word: 'SELITTÄÄ', translation: 'to explain', translation_es: 'explicar', translation_sv: 'att förklara', difficulty: 'medium', category: 'verb' },
  { word: 'KYSYÄ', translation: 'to ask', translation_es: 'preguntar', translation_sv: 'att fråga', difficulty: 'medium', category: 'verb' },
  { word: 'VASTATA', translation: 'to answer', translation_es: 'responder', translation_sv: 'att svara', difficulty: 'medium', category: 'verb' },
  { word: 'KERTOA', translation: 'to tell', translation_es: 'contar', translation_sv: 'att berätta', difficulty: 'medium', category: 'verb' },
  { word: 'KUUNNELLA', translation: 'to listen', translation_es: 'escuchar', translation_sv: 'att lyssna', difficulty: 'medium', category: 'verb' },
  { word: 'OPETTAA', translation: 'to teach', translation_es: 'enseñar', translation_sv: 'att undervisa', difficulty: 'medium', category: 'verb' },
  { word: 'OPISKELLA', translation: 'to study', translation_es: 'estudiar', translation_sv: 'att studera', difficulty: 'medium', category: 'verb' },
  { word: 'HARJOITELLA', translation: 'to practice', translation_es: 'practicar', translation_sv: 'att öva', difficulty: 'medium', category: 'verb' },
  { word: 'YRITTÄÄ', translation: 'to try', translation_es: 'intentar', translation_sv: 'att försöka', difficulty: 'medium', category: 'verb' },
  { word: 'ONNISTUA', translation: 'to succeed', translation_es: 'tener éxito', translation_sv: 'att lyckas', difficulty: 'medium', category: 'verb' },
  { word: 'EPÄONNISTUA', translation: 'to fail', translation_es: 'fracasar', translation_sv: 'att misslyckas', difficulty: 'medium', category: 'verb' },
  { word: 'ALOITTAA', translation: 'to begin', translation_es: 'empezar', translation_sv: 'att börja', difficulty: 'medium', category: 'verb' },
  { word: 'LOPETTAA', translation: 'to stop', translation_es: 'parar', translation_sv: 'att sluta', difficulty: 'medium', category: 'verb' },
  { word: 'JATKAA', translation: 'to continue', translation_es: 'continuar', translation_sv: 'att fortsätta', difficulty: 'medium', category: 'verb' },
  { word: 'VAIHTAA', translation: 'to change', translation_es: 'cambiar', translation_sv: 'att byta', difficulty: 'medium', category: 'verb' },
  { word: 'KORJATA', translation: 'to fix', translation_es: 'arreglar', translation_sv: 'att laga', difficulty: 'medium', category: 'verb' },
  { word: 'RAKENTAA', translation: 'to build', translation_es: 'construir', translation_sv: 'att bygga', difficulty: 'medium', category: 'verb' },
  { word: 'RIKKOA', translation: 'to break', translation_es: 'romper', translation_sv: 'att bryta', difficulty: 'medium', category: 'verb' },
  { word: 'LEIKATA', translation: 'to cut', translation_es: 'cortar', translation_sv: 'att klippa', difficulty: 'medium', category: 'verb' },
  { word: 'SIIVOTA', translation: 'to clean', translation_es: 'limpiar', translation_sv: 'att städa', difficulty: 'medium', category: 'verb' },
  { word: 'LAITTAA', translation: 'to put', translation_es: 'poner', translation_sv: 'att lägga', difficulty: 'medium', category: 'verb' },
  { word: 'KOKEILLA', translation: 'to try out', translation_es: 'probar', translation_sv: 'att prova', difficulty: 'medium', category: 'verb' },
  { word: 'VALITA', translation: 'to choose', translation_es: 'elegir', translation_sv: 'att välja', difficulty: 'medium', category: 'verb' },
  { word: 'PÄÄTTÄÄ', translation: 'to decide', translation_es: 'decidir', translation_sv: 'att bestämma', difficulty: 'medium', category: 'verb' },
  { word: 'SUUNNITELLA', translation: 'to plan', translation_es: 'planificar', translation_sv: 'att planera', difficulty: 'medium', category: 'verb' },
  { word: 'VALMISTAA', translation: 'to prepare', translation_es: 'preparar', translation_sv: 'att förbereda', difficulty: 'medium', category: 'verb' },
  { word: 'KEITTÄÄ', translation: 'to cook', translation_es: 'cocinar', translation_sv: 'att koka', difficulty: 'medium', category: 'verb' },
  { word: 'PAISTAA', translation: 'to fry', translation_es: 'freír', translation_sv: 'att steka', difficulty: 'medium', category: 'verb' },
  { word: 'LEIPOA', translation: 'to bake', translation_es: 'hornear', translation_sv: 'att baka', difficulty: 'medium', category: 'verb' },
  { word: 'MAISTAA', translation: 'to taste', translation_es: 'probar', translation_sv: 'att smaka', difficulty: 'medium', category: 'verb' },
  { word: 'HAISTAA', translation: 'to smell', translation_es: 'oler', translation_sv: 'att lukta', difficulty: 'medium', category: 'verb' },
  { word: 'KOSKETTAA', translation: 'to touch', translation_es: 'tocar', translation_sv: 'att röra', difficulty: 'medium', category: 'verb' },
  { word: 'TYÖNTÄÄ', translation: 'to push', translation_es: 'empujar', translation_sv: 'att trycka', difficulty: 'medium', category: 'verb' },
  { word: 'VETÄÄ', translation: 'to pull', translation_es: 'tirar', translation_sv: 'att dra', difficulty: 'medium', category: 'verb' },
  { word: 'NOSTAA', translation: 'to lift', translation_es: 'levantar', translation_sv: 'att lyfta', difficulty: 'medium', category: 'verb' },
  { word: 'LASKEA', translation: 'to count', translation_es: 'contar', translation_sv: 'att räkna', difficulty: 'medium', category: 'verb' },
  { word: 'MITATA', translation: 'to measure', translation_es: 'medir', translation_sv: 'att mäta', difficulty: 'medium', category: 'verb' },
  { word: 'PUNNITA', translation: 'to weigh', translation_es: 'pesar', translation_sv: 'att väga', difficulty: 'medium', category: 'verb' },
  { word: 'MAALATA', translation: 'to paint', translation_es: 'pintar', translation_sv: 'att måla', difficulty: 'medium', category: 'verb' },
  { word: 'SOITTAA', translation: 'to play', translation_es: 'tocar', translation_sv: 'att spela', difficulty: 'medium', category: 'verb' },
  { word: 'VALOKUVATA', translation: 'to photograph', translation_es: 'fotografiar', translation_sv: 'att fotografera', difficulty: 'medium', category: 'verb' },
  { word: 'MATKUSTAA', translation: 'to travel', translation_es: 'viajar', translation_sv: 'att resa', difficulty: 'medium', category: 'verb' },
  { word: 'AJAA', translation: 'to drive', translation_es: 'conducir', translation_sv: 'att köra', difficulty: 'medium', category: 'verb' },
  { word: 'PYSÄHTYÄ', translation: 'to stop', translation_es: 'detenerse', translation_sv: 'att stanna', difficulty: 'medium', category: 'verb' },
  { word: 'KÄÄNTYÄ', translation: 'to turn', translation_es: 'girar', translation_sv: 'att svänga', difficulty: 'medium', category: 'verb' },
  { word: 'PALATA', translation: 'to return', translation_es: 'volver', translation_sv: 'att återvända', difficulty: 'medium', category: 'verb' },

  // --- Hard verbs (~50) ---
  { word: 'KESKUSTELLA', translation: 'to discuss', translation_es: 'discutir', translation_sv: 'att diskutera', difficulty: 'hard', category: 'verb' },
  { word: 'VÄITELLÄ', translation: 'to debate', translation_es: 'debatir', translation_sv: 'att debattera', difficulty: 'hard', category: 'verb' },
  { word: 'NEUVOTELLA', translation: 'to negotiate', translation_es: 'negociar', translation_sv: 'att förhandla', difficulty: 'hard', category: 'verb' },
  { word: 'EHDOTTAA', translation: 'to suggest', translation_es: 'sugerir', translation_sv: 'att föreslå', difficulty: 'hard', category: 'verb' },
  { word: 'HYVÄKSYÄ', translation: 'to accept', translation_es: 'aceptar', translation_sv: 'att acceptera', difficulty: 'hard', category: 'verb' },
  { word: 'KIELTÄYTYÄ', translation: 'to refuse', translation_es: 'rechazar', translation_sv: 'att vägra', difficulty: 'hard', category: 'verb' },
  { word: 'ANTEEKSIANTAA', translation: 'to forgive', translation_es: 'perdonar', translation_sv: 'att förlåta', difficulty: 'hard', category: 'verb' },
  { word: 'LUOTTAA', translation: 'to trust', translation_es: 'confiar', translation_sv: 'att lita på', difficulty: 'hard', category: 'verb' },
  { word: 'IHMETELLÄ', translation: 'to wonder', translation_es: 'preguntarse', translation_sv: 'att undra', difficulty: 'hard', category: 'verb' },
  { word: 'TUTKIA', translation: 'to explore', translation_es: 'explorar', translation_sv: 'att utforska', difficulty: 'hard', category: 'verb' },
  { word: 'KEKSIÄ', translation: 'to invent', translation_es: 'inventar', translation_sv: 'att uppfinna', difficulty: 'hard', category: 'verb' },
  { word: 'HUOMATA', translation: 'to notice', translation_es: 'notar', translation_sv: 'att märka', difficulty: 'hard', category: 'verb' },
  { word: 'ARVOSTAA', translation: 'to appreciate', translation_es: 'apreciar', translation_sv: 'att uppskatta', difficulty: 'hard', category: 'verb' },
  { word: 'KANNUSTAA', translation: 'to encourage', translation_es: 'animar', translation_sv: 'att uppmuntra', difficulty: 'hard', category: 'verb' },
  { word: 'ROHKAISTA', translation: 'to embolden', translation_es: 'envalentonar', translation_sv: 'att inge mod', difficulty: 'hard', category: 'verb' },
  { word: 'PELÄSTYÄ', translation: 'to get scared', translation_es: 'asustarse', translation_sv: 'att bli rädd', difficulty: 'hard', category: 'verb' },
  { word: 'HÄMMÄSTYÄ', translation: 'to be amazed', translation_es: 'asombrarse', translation_sv: 'att bli förvånad', difficulty: 'hard', category: 'verb' },
  { word: 'INNOSTUA', translation: 'to get excited', translation_es: 'emocionarse', translation_sv: 'att bli entusiastisk', difficulty: 'hard', category: 'verb' },
  { word: 'RENTOUTUA', translation: 'to relax', translation_es: 'relajarse', translation_sv: 'att slappna av', difficulty: 'hard', category: 'verb' },
  { word: 'VALMISTAUTUA', translation: 'to prepare oneself', translation_es: 'prepararse', translation_sv: 'att förbereda sig', difficulty: 'hard', category: 'verb' },
  { word: 'KUNTOILLA', translation: 'to exercise', translation_es: 'hacer ejercicio', translation_sv: 'att träna', difficulty: 'hard', category: 'verb' },
  { word: 'HIIHTÄÄ', translation: 'to ski', translation_es: 'esquiar', translation_sv: 'att åka skidor', difficulty: 'hard', category: 'verb' },
  { word: 'LUISTELLA', translation: 'to ice skate', translation_es: 'patinar sobre hielo', translation_sv: 'att åka skridskor', difficulty: 'hard', category: 'verb' },
  { word: 'RATSASTAA', translation: 'to ride', translation_es: 'montar a caballo', translation_sv: 'att rida', difficulty: 'hard', category: 'verb' },
  { word: 'PURJEHTIA', translation: 'to sail', translation_es: 'navegar', translation_sv: 'att segla', difficulty: 'hard', category: 'verb' },
  { word: 'KIIPEILLÄ', translation: 'to climb', translation_es: 'escalar', translation_sv: 'att klättra', difficulty: 'hard', category: 'verb' },
  { word: 'SUKELTAA', translation: 'to dive', translation_es: 'bucear', translation_sv: 'att dyka', difficulty: 'hard', category: 'verb' },
  { word: 'KALASTAA', translation: 'to fish', translation_es: 'pescar', translation_sv: 'att fiska', difficulty: 'hard', category: 'verb' },
  { word: 'MARJASTAA', translation: 'to pick berries', translation_es: 'recoger bayas', translation_sv: 'att plocka bär', difficulty: 'hard', category: 'verb' },
  { word: 'SIENESTÄÄ', translation: 'to pick mushrooms', translation_es: 'recoger setas', translation_sv: 'att plocka svamp', difficulty: 'hard', category: 'verb' },
  { word: 'PUUTARHOIDA', translation: 'to garden', translation_es: 'hacer jardinería', translation_sv: 'att odla', difficulty: 'hard', category: 'verb' },
  { word: 'KOMPOSTOIDA', translation: 'to compost', translation_es: 'compostar', translation_sv: 'att kompostera', difficulty: 'hard', category: 'verb' },
  { word: 'KIERRÄTTÄÄ', translation: 'to recycle', translation_es: 'reciclar', translation_sv: 'att återvinna', difficulty: 'hard', category: 'verb' },
  { word: 'SÄÄSTÄÄ', translation: 'to save', translation_es: 'ahorrar', translation_sv: 'att spara', difficulty: 'hard', category: 'verb' },
  { word: 'INVESTOIDA', translation: 'to invest', translation_es: 'invertir', translation_sv: 'att investera', difficulty: 'hard', category: 'verb' },
  { word: 'ORGANISOIDA', translation: 'to organize', translation_es: 'organizar', translation_sv: 'att organisera', difficulty: 'hard', category: 'verb' },
  { word: 'KOORDINOIDA', translation: 'to coordinate', translation_es: 'coordinar', translation_sv: 'att koordinera', difficulty: 'hard', category: 'verb' },
  { word: 'KOMMUNIKOIDA', translation: 'to communicate', translation_es: 'comunicar', translation_sv: 'att kommunicera', difficulty: 'hard', category: 'verb' },
  { word: 'DOKUMENTOIDA', translation: 'to document', translation_es: 'documentar', translation_sv: 'att dokumentera', difficulty: 'hard', category: 'verb' },
  { word: 'ANALYSOIDA', translation: 'to analyze', translation_es: 'analizar', translation_sv: 'att analysera', difficulty: 'hard', category: 'verb' },
  { word: 'VERTAILLA', translation: 'to compare', translation_es: 'comparar', translation_sv: 'att jämföra', difficulty: 'hard', category: 'verb' },
  { word: 'ARVIOIDA', translation: 'to evaluate', translation_es: 'evaluar', translation_sv: 'att utvärdera', difficulty: 'hard', category: 'verb' },
  { word: 'KEHITTÄÄ', translation: 'to develop', translation_es: 'desarrollar', translation_sv: 'att utveckla', difficulty: 'hard', category: 'verb' },
  { word: 'PARANTAA', translation: 'to improve', translation_es: 'mejorar', translation_sv: 'att förbättra', difficulty: 'hard', category: 'verb' },
  { word: 'VAHVISTAA', translation: 'to strengthen', translation_es: 'fortalecer', translation_sv: 'att stärka', difficulty: 'hard', category: 'verb' },
  { word: 'HEIKENTÄÄ', translation: 'to weaken', translation_es: 'debilitar', translation_sv: 'att försvaga', difficulty: 'hard', category: 'verb' },
  { word: 'LAAJENTAA', translation: 'to expand', translation_es: 'expandir', translation_sv: 'att utvidga', difficulty: 'hard', category: 'verb' },
  { word: 'SUPISTAA', translation: 'to shrink', translation_es: 'reducir', translation_sv: 'att krympa', difficulty: 'hard', category: 'verb' },
  { word: 'YHDISTÄÄ', translation: 'to combine', translation_es: 'combinar', translation_sv: 'att kombinera', difficulty: 'hard', category: 'verb' },
  { word: 'EROTTAA', translation: 'to separate', translation_es: 'separar', translation_sv: 'att separera', difficulty: 'hard', category: 'verb' },

  // ============================================================
  // ADJECTIVES
  // ============================================================

  // --- Easy adjectives (~50) ---
  { word: 'ISO', translation: 'big', translation_es: 'grande', translation_sv: 'stor', difficulty: 'easy', category: 'adjective' },
  { word: 'PIENI', translation: 'small', translation_es: 'pequeño', translation_sv: 'liten', difficulty: 'easy', category: 'adjective' },
  { word: 'HYVÄ', translation: 'good', translation_es: 'bueno', translation_sv: 'bra', difficulty: 'easy', category: 'adjective' },
  { word: 'PAHA', translation: 'bad', translation_es: 'malo', translation_sv: 'dålig', difficulty: 'easy', category: 'adjective' },
  { word: 'UUSI', translation: 'new', translation_es: 'nuevo', translation_sv: 'ny', difficulty: 'easy', category: 'adjective' },
  { word: 'VANHA', translation: 'old', translation_es: 'viejo', translation_sv: 'gammal', difficulty: 'easy', category: 'adjective' },
  { word: 'KUUMA', translation: 'hot', translation_es: 'caliente', translation_sv: 'het', difficulty: 'easy', category: 'adjective' },
  { word: 'KYLMÄ', translation: 'cold', translation_es: 'frío', translation_sv: 'kall', difficulty: 'easy', category: 'adjective' },
  { word: 'NOPEA', translation: 'fast', translation_es: 'rápido', translation_sv: 'snabb', difficulty: 'easy', category: 'adjective' },
  { word: 'HIDAS', translation: 'slow', translation_es: 'lento', translation_sv: 'långsam', difficulty: 'easy', category: 'adjective' },
  { word: 'KAUNIS', translation: 'beautiful', translation_es: 'hermoso', translation_sv: 'vacker', difficulty: 'easy', category: 'adjective' },
  { word: 'RUMA', translation: 'ugly', translation_es: 'feo', translation_sv: 'ful', difficulty: 'easy', category: 'adjective' },
  { word: 'PITKÄ', translation: 'long', translation_es: 'largo', translation_sv: 'lång', difficulty: 'easy', category: 'adjective' },
  { word: 'LYHYT', translation: 'short', translation_es: 'corto', translation_sv: 'kort', difficulty: 'easy', category: 'adjective' },
  { word: 'LEVEÄ', translation: 'wide', translation_es: 'ancho', translation_sv: 'bred', difficulty: 'easy', category: 'adjective' },
  { word: 'KAPEA', translation: 'narrow', translation_es: 'estrecho', translation_sv: 'smal', difficulty: 'easy', category: 'adjective' },
  { word: 'RASKAS', translation: 'heavy', translation_es: 'pesado', translation_sv: 'tung', difficulty: 'easy', category: 'adjective' },
  { word: 'KEVYT', translation: 'light', translation_es: 'ligero', translation_sv: 'lätt', difficulty: 'easy', category: 'adjective' },
  { word: 'KOVA', translation: 'hard', translation_es: 'duro', translation_sv: 'hård', difficulty: 'easy', category: 'adjective' },
  { word: 'PEHMEÄ', translation: 'soft', translation_es: 'suave', translation_sv: 'mjuk', difficulty: 'easy', category: 'adjective' },
  { word: 'MÄRKÄ', translation: 'wet', translation_es: 'mojado', translation_sv: 'blöt', difficulty: 'easy', category: 'adjective' },
  { word: 'KUIVA', translation: 'dry', translation_es: 'seco', translation_sv: 'torr', difficulty: 'easy', category: 'adjective' },
  { word: 'PUNAINEN', translation: 'red', translation_es: 'rojo', translation_sv: 'röd', difficulty: 'easy', category: 'adjective' },
  { word: 'SININEN', translation: 'blue', translation_es: 'azul', translation_sv: 'blå', difficulty: 'easy', category: 'adjective' },
  { word: 'VIHREÄ', translation: 'green', translation_es: 'verde', translation_sv: 'grön', difficulty: 'easy', category: 'adjective' },
  { word: 'KELTAINEN', translation: 'yellow', translation_es: 'amarillo', translation_sv: 'gul', difficulty: 'easy', category: 'adjective' },
  { word: 'VALKOINEN', translation: 'white', translation_es: 'blanco', translation_sv: 'vit', difficulty: 'easy', category: 'adjective' },
  { word: 'MUSTA', translation: 'black', translation_es: 'negro', translation_sv: 'svart', difficulty: 'easy', category: 'adjective' },
  { word: 'HARMAA', translation: 'gray', translation_es: 'gris', translation_sv: 'grå', difficulty: 'easy', category: 'adjective' },
  { word: 'RUSKEA', translation: 'brown', translation_es: 'marrón', translation_sv: 'brun', difficulty: 'easy', category: 'adjective' },
  { word: 'VAALEA', translation: 'light', translation_es: 'claro', translation_sv: 'ljus', difficulty: 'easy', category: 'adjective' },
  { word: 'TUMMA', translation: 'dark', translation_es: 'oscuro', translation_sv: 'mörk', difficulty: 'easy', category: 'adjective' },
  { word: 'ILOINEN', translation: 'happy', translation_es: 'alegre', translation_sv: 'glad', difficulty: 'easy', category: 'adjective' },
  { word: 'SURULLINEN', translation: 'sad', translation_es: 'triste', translation_sv: 'ledsen', difficulty: 'easy', category: 'adjective' },
  { word: 'VIHAINEN', translation: 'angry', translation_es: 'enfadado', translation_sv: 'arg', difficulty: 'easy', category: 'adjective' },
  { word: 'VÄSYNYT', translation: 'tired', translation_es: 'cansado', translation_sv: 'trött', difficulty: 'easy', category: 'adjective' },
  { word: 'NÄLKÄINEN', translation: 'hungry', translation_es: 'hambriento', translation_sv: 'hungrig', difficulty: 'easy', category: 'adjective' },
  { word: 'JANOINEN', translation: 'thirsty', translation_es: 'sediento', translation_sv: 'törstig', difficulty: 'easy', category: 'adjective' },
  { word: 'TERVE', translation: 'healthy', translation_es: 'sano', translation_sv: 'frisk', difficulty: 'easy', category: 'adjective' },
  { word: 'SAIRAS', translation: 'sick', translation_es: 'enfermo', translation_sv: 'sjuk', difficulty: 'easy', category: 'adjective' },
  { word: 'VAHVA', translation: 'strong', translation_es: 'fuerte', translation_sv: 'stark', difficulty: 'easy', category: 'adjective' },
  { word: 'HEIKKO', translation: 'weak', translation_es: 'débil', translation_sv: 'svag', difficulty: 'easy', category: 'adjective' },
  { word: 'RIKAS', translation: 'rich', translation_es: 'rico', translation_sv: 'rik', difficulty: 'easy', category: 'adjective' },
  { word: 'KÖYHÄ', translation: 'poor', translation_es: 'pobre', translation_sv: 'fattig', difficulty: 'easy', category: 'adjective' },
  { word: 'NUORI', translation: 'young', translation_es: 'joven', translation_sv: 'ung', difficulty: 'easy', category: 'adjective' },
  { word: 'KILTTI', translation: 'kind', translation_es: 'amable', translation_sv: 'snäll', difficulty: 'easy', category: 'adjective' },
  { word: 'ROHKEA', translation: 'brave', translation_es: 'valiente', translation_sv: 'modig', difficulty: 'easy', category: 'adjective' },
  { word: 'ARKA', translation: 'shy', translation_es: 'tímido', translation_sv: 'blyg', difficulty: 'easy', category: 'adjective' },
  { word: 'HAUSKA', translation: 'funny', translation_es: 'gracioso', translation_sv: 'rolig', difficulty: 'easy', category: 'adjective' },
  { word: 'HASSU', translation: 'silly', translation_es: 'tonto', translation_sv: 'fånig', difficulty: 'easy', category: 'adjective' },

  // --- Medium adjectives (~50) ---
  { word: 'YSTÄVÄLLINEN', translation: 'friendly', translation_es: 'amigable', translation_sv: 'vänlig', difficulty: 'medium', category: 'adjective' },
  { word: 'VIISAS', translation: 'wise', translation_es: 'sabio', translation_sv: 'vis', difficulty: 'medium', category: 'adjective' },
  { word: 'TYHMÄ', translation: 'stupid', translation_es: 'estúpido', translation_sv: 'dum', difficulty: 'medium', category: 'adjective' },
  { word: 'AHKERA', translation: 'diligent', translation_es: 'diligente', translation_sv: 'flitig', difficulty: 'medium', category: 'adjective' },
  { word: 'LAISKA', translation: 'lazy', translation_es: 'perezoso', translation_sv: 'lat', difficulty: 'medium', category: 'adjective' },
  { word: 'RAUHALLINEN', translation: 'calm', translation_es: 'tranquilo', translation_sv: 'lugn', difficulty: 'medium', category: 'adjective' },
  { word: 'LEVOTON', translation: 'restless', translation_es: 'inquieto', translation_sv: 'rastlös', difficulty: 'medium', category: 'adjective' },
  { word: 'UTELIAS', translation: 'curious', translation_es: 'curioso', translation_sv: 'nyfiken', difficulty: 'medium', category: 'adjective' },
  { word: 'HUOLELLINEN', translation: 'careful', translation_es: 'cuidadoso', translation_sv: 'försiktig', difficulty: 'medium', category: 'adjective' },
  { word: 'HUOLIMATON', translation: 'careless', translation_es: 'descuidado', translation_sv: 'vårdslös', difficulty: 'medium', category: 'adjective' },
  { word: 'REHELLINEN', translation: 'honest', translation_es: 'honesto', translation_sv: 'ärlig', difficulty: 'medium', category: 'adjective' },
  { word: 'LUOTETTAVA', translation: 'reliable', translation_es: 'confiable', translation_sv: 'pålitlig', difficulty: 'medium', category: 'adjective' },
  { word: 'KÄRSIVÄLLINEN', translation: 'patient', translation_es: 'paciente', translation_sv: 'tålamodig', difficulty: 'medium', category: 'adjective' },
  { word: 'KÄRSIMÄTÖN', translation: 'impatient', translation_es: 'impaciente', translation_sv: 'otålig', difficulty: 'medium', category: 'adjective' },
  { word: 'TYYTYVÄINEN', translation: 'satisfied', translation_es: 'satisfecho', translation_sv: 'nöjd', difficulty: 'medium', category: 'adjective' },
  { word: 'TYYTYMÄTÖN', translation: 'dissatisfied', translation_es: 'insatisfecho', translation_sv: 'missnöjd', difficulty: 'medium', category: 'adjective' },
  { word: 'ONNELLINEN', translation: 'happy', translation_es: 'feliz', translation_sv: 'lycklig', difficulty: 'medium', category: 'adjective' },
  { word: 'PELOKAS', translation: 'fearful', translation_es: 'temeroso', translation_sv: 'rädd', difficulty: 'medium', category: 'adjective' },
  { word: 'YLPEÄ', translation: 'proud', translation_es: 'orgulloso', translation_sv: 'stolt', difficulty: 'medium', category: 'adjective' },
  { word: 'NÖYRÄ', translation: 'humble', translation_es: 'humilde', translation_sv: 'ödmjuk', difficulty: 'medium', category: 'adjective' },
  { word: 'TÄYDELLINEN', translation: 'perfect', translation_es: 'perfecto', translation_sv: 'perfekt', difficulty: 'medium', category: 'adjective' },
  { word: 'TAVALLINEN', translation: 'ordinary', translation_es: 'ordinario', translation_sv: 'vanlig', difficulty: 'medium', category: 'adjective' },
  { word: 'ERIKOINEN', translation: 'special', translation_es: 'especial', translation_sv: 'speciell', difficulty: 'medium', category: 'adjective' },
  { word: 'TÄRKEÄ', translation: 'important', translation_es: 'importante', translation_sv: 'viktig', difficulty: 'medium', category: 'adjective' },
  { word: 'TURHA', translation: 'useless', translation_es: 'inútil', translation_sv: 'onödig', difficulty: 'medium', category: 'adjective' },
  { word: 'HYÖDYLLINEN', translation: 'useful', translation_es: 'útil', translation_sv: 'användbar', difficulty: 'medium', category: 'adjective' },
  { word: 'VAARALLINEN', translation: 'dangerous', translation_es: 'peligroso', translation_sv: 'farlig', difficulty: 'medium', category: 'adjective' },
  { word: 'TURVALLINEN', translation: 'safe', translation_es: 'seguro', translation_sv: 'säker', difficulty: 'medium', category: 'adjective' },
  { word: 'HELPPO', translation: 'easy', translation_es: 'fácil', translation_sv: 'lätt', difficulty: 'medium', category: 'adjective' },
  { word: 'VAIKEA', translation: 'difficult', translation_es: 'difícil', translation_sv: 'svår', difficulty: 'medium', category: 'adjective' },
  { word: 'MIELENKIINTOINEN', translation: 'interesting', translation_es: 'interesante', translation_sv: 'intressant', difficulty: 'medium', category: 'adjective' },
  { word: 'TYLSÄ', translation: 'boring', translation_es: 'aburrido', translation_sv: 'tråkig', difficulty: 'medium', category: 'adjective' },
  { word: 'JÄNNITTÄVÄ', translation: 'exciting', translation_es: 'emocionante', translation_sv: 'spännande', difficulty: 'medium', category: 'adjective' },
  { word: 'PELOTTAVA', translation: 'scary', translation_es: 'aterrador', translation_sv: 'läskig', difficulty: 'medium', category: 'adjective' },
  { word: 'HAUSKA', translation: 'fun', translation_es: 'divertido', translation_sv: 'rolig', difficulty: 'medium', category: 'adjective' },
  { word: 'MAKEA', translation: 'sweet', translation_es: 'dulce', translation_sv: 'söt', difficulty: 'medium', category: 'adjective' },
  { word: 'SUOLAINEN', translation: 'salty', translation_es: 'salado', translation_sv: 'salt', difficulty: 'medium', category: 'adjective' },
  { word: 'HAPAN', translation: 'sour', translation_es: 'ácido', translation_sv: 'sur', difficulty: 'medium', category: 'adjective' },
  { word: 'KITKERÄ', translation: 'bitter', translation_es: 'amargo', translation_sv: 'bitter', difficulty: 'medium', category: 'adjective' },
  { word: 'MAUSTEINEN', translation: 'spicy', translation_es: 'picante', translation_sv: 'kryddig', difficulty: 'medium', category: 'adjective' },
  { word: 'TUORE', translation: 'fresh', translation_es: 'fresco', translation_sv: 'färsk', difficulty: 'medium', category: 'adjective' },
  { word: 'MEHUKAS', translation: 'juicy', translation_es: 'jugoso', translation_sv: 'saftig', difficulty: 'medium', category: 'adjective' },
  { word: 'RAPEA', translation: 'crispy', translation_es: 'crujiente', translation_sv: 'knaprig', difficulty: 'medium', category: 'adjective' },
  { word: 'LÄMMIN', translation: 'warm', translation_es: 'cálido', translation_sv: 'varm', difficulty: 'medium', category: 'adjective' },
  { word: 'VIILEÄ', translation: 'cool', translation_es: 'fresco', translation_sv: 'sval', difficulty: 'medium', category: 'adjective' },
  { word: 'KIRKAS', translation: 'bright', translation_es: 'brillante', translation_sv: 'ljus', difficulty: 'medium', category: 'adjective' },
  { word: 'HIMMEÄ', translation: 'dim', translation_es: 'tenue', translation_sv: 'svag', difficulty: 'medium', category: 'adjective' },
  { word: 'HILJAINEN', translation: 'quiet', translation_es: 'silencioso', translation_sv: 'tyst', difficulty: 'medium', category: 'adjective' },
  { word: 'ÄÄNEKÄS', translation: 'loud', translation_es: 'ruidoso', translation_sv: 'hög', difficulty: 'medium', category: 'adjective' },
  { word: 'PYÖREÄ', translation: 'round', translation_es: 'redondo', translation_sv: 'rund', difficulty: 'medium', category: 'adjective' },

  // --- Hard adjectives (~50) ---
  { word: 'NELIKULMAINEN', translation: 'square-shaped', translation_es: 'cuadrado', translation_sv: 'fyrkantig', difficulty: 'hard', category: 'adjective' },
  { word: 'KOLMIONMUOTOINEN', translation: 'triangular', translation_es: 'triangular', translation_sv: 'trekantig', difficulty: 'hard', category: 'adjective' },
  { word: 'SUORAKAITEEN', translation: 'rectangular', translation_es: 'rectangular', translation_sv: 'rektangulär', difficulty: 'hard', category: 'adjective' },
  { word: 'SYMMETRINEN', translation: 'symmetrical', translation_es: 'simétrico', translation_sv: 'symmetrisk', difficulty: 'hard', category: 'adjective' },
  { word: 'EPÄSYMMETRINEN', translation: 'asymmetrical', translation_es: 'asimétrico', translation_sv: 'asymmetrisk', difficulty: 'hard', category: 'adjective' },
  { word: 'LÄPINÄKYVÄ', translation: 'transparent', translation_es: 'transparente', translation_sv: 'genomskinlig', difficulty: 'hard', category: 'adjective' },
  { word: 'LÄPINÄKYMÄTÖN', translation: 'opaque', translation_es: 'opaco', translation_sv: 'ogenomskinlig', difficulty: 'hard', category: 'adjective' },
  { word: 'KIILTÄVÄ', translation: 'shiny', translation_es: 'brillante', translation_sv: 'blank', difficulty: 'hard', category: 'adjective' },
  { word: 'MATTAPINTAINEN', translation: 'matte', translation_es: 'mate', translation_sv: 'matt', difficulty: 'hard', category: 'adjective' },
  { word: 'KARHEA', translation: 'rough', translation_es: 'áspero', translation_sv: 'grov', difficulty: 'hard', category: 'adjective' },
  { word: 'SILEÄ', translation: 'smooth', translation_es: 'liso', translation_sv: 'slät', difficulty: 'hard', category: 'adjective' },
  { word: 'LIUKAS', translation: 'slippery', translation_es: 'resbaladizo', translation_sv: 'hal', difficulty: 'hard', category: 'adjective' },
  { word: 'TAHMEA', translation: 'sticky', translation_es: 'pegajoso', translation_sv: 'klibbig', difficulty: 'hard', category: 'adjective' },
  { word: 'JOUSTAVA', translation: 'flexible', translation_es: 'flexible', translation_sv: 'flexibel', difficulty: 'hard', category: 'adjective' },
  { word: 'JÄYKKÄ', translation: 'stiff', translation_es: 'rígido', translation_sv: 'styv', difficulty: 'hard', category: 'adjective' },
  { word: 'HAURAS', translation: 'fragile', translation_es: 'frágil', translation_sv: 'skör', difficulty: 'hard', category: 'adjective' },
  { word: 'KESTÄVÄ', translation: 'durable', translation_es: 'duradero', translation_sv: 'hållbar', difficulty: 'hard', category: 'adjective' },
  { word: 'VEDENPITÄVÄ', translation: 'waterproof', translation_es: 'impermeable', translation_sv: 'vattentät', difficulty: 'hard', category: 'adjective' },
  { word: 'TULENKESTÄVÄ', translation: 'fireproof', translation_es: 'ignífugo', translation_sv: 'brandsäker', difficulty: 'hard', category: 'adjective' },
  { word: 'MYRKYLLINEN', translation: 'poisonous', translation_es: 'venenoso', translation_sv: 'giftig', difficulty: 'hard', category: 'adjective' },
  { word: 'MYRKYTÖN', translation: 'non-toxic', translation_es: 'no tóxico', translation_sv: 'giftfri', difficulty: 'hard', category: 'adjective' },
  { word: 'LUONNOLLINEN', translation: 'natural', translation_es: 'natural', translation_sv: 'naturlig', difficulty: 'hard', category: 'adjective' },
  { word: 'KEINOTEKOINEN', translation: 'artificial', translation_es: 'artificial', translation_sv: 'konstgjord', difficulty: 'hard', category: 'adjective' },
  { word: 'ALKUPERÄINEN', translation: 'original', translation_es: 'original', translation_sv: 'ursprunglig', difficulty: 'hard', category: 'adjective' },
  { word: 'MODERNI', translation: 'modern', translation_es: 'moderno', translation_sv: 'modern', difficulty: 'hard', category: 'adjective' },
  { word: 'VANHANAIKAINEN', translation: 'old-fashioned', translation_es: 'anticuado', translation_sv: 'gammaldags', difficulty: 'hard', category: 'adjective' },
  { word: 'PERINTEINEN', translation: 'traditional', translation_es: 'tradicional', translation_sv: 'traditionell', difficulty: 'hard', category: 'adjective' },
  { word: 'NYKYAIKAINEN', translation: 'contemporary', translation_es: 'contemporáneo', translation_sv: 'samtida', difficulty: 'hard', category: 'adjective' },
  { word: 'KANSAINVÄLINEN', translation: 'international', translation_es: 'internacional', translation_sv: 'internationell', difficulty: 'hard', category: 'adjective' },
  { word: 'PAIKALLINEN', translation: 'local', translation_es: 'local', translation_sv: 'lokal', difficulty: 'hard', category: 'adjective' },
  { word: 'MAAILMANLAAJUINEN', translation: 'worldwide', translation_es: 'mundial', translation_sv: 'världsomfattande', difficulty: 'hard', category: 'adjective' },
  { word: 'YMPÄRISTÖYSTÄVÄLLINEN', translation: 'eco-friendly', translation_es: 'ecológico', translation_sv: 'miljövänlig', difficulty: 'hard', category: 'adjective' },
  { word: 'VASTUULLINEN', translation: 'responsible', translation_es: 'responsable', translation_sv: 'ansvarsfull', difficulty: 'hard', category: 'adjective' },
  { word: 'VASTUUTON', translation: 'irresponsible', translation_es: 'irresponsable', translation_sv: 'oansvarig', difficulty: 'hard', category: 'adjective' },
  { word: 'ITSENÄINEN', translation: 'independent', translation_es: 'independiente', translation_sv: 'självständig', difficulty: 'hard', category: 'adjective' },
  { word: 'RIIPPUVAINEN', translation: 'dependent', translation_es: 'dependiente', translation_sv: 'beroende', difficulty: 'hard', category: 'adjective' },
  { word: 'MONIPUOLINEN', translation: 'versatile', translation_es: 'versátil', translation_sv: 'mångsidig', difficulty: 'hard', category: 'adjective' },
  { word: 'YKSIPUOLINEN', translation: 'one-sided', translation_es: 'unilateral', translation_sv: 'ensidig', difficulty: 'hard', category: 'adjective' },
  { word: 'AMMATTITAITOINEN', translation: 'professional', translation_es: 'profesional', translation_sv: 'professionell', difficulty: 'hard', category: 'adjective' },
  { word: 'KOKEMATON', translation: 'inexperienced', translation_es: 'inexperto', translation_sv: 'oerfaren', difficulty: 'hard', category: 'adjective' },
  { word: 'KOKENUT', translation: 'experienced', translation_es: 'experimentado', translation_sv: 'erfaren', difficulty: 'hard', category: 'adjective' },
  { word: 'LUOVA', translation: 'creative', translation_es: 'creativo', translation_sv: 'kreativ', difficulty: 'hard', category: 'adjective' },
  { word: 'JÄRJESTELMÄLLINEN', translation: 'systematic', translation_es: 'sistemático', translation_sv: 'systematisk', difficulty: 'hard', category: 'adjective' },
  { word: 'SPONTAANI', translation: 'spontaneous', translation_es: 'espontáneo', translation_sv: 'spontan', difficulty: 'hard', category: 'adjective' },
  { word: 'PÄÄTTÄVÄINEN', translation: 'determined', translation_es: 'determinado', translation_sv: 'bestämd', difficulty: 'hard', category: 'adjective' },
  { word: 'EMPAATTINEN', translation: 'empathetic', translation_es: 'empático', translation_sv: 'empatisk', difficulty: 'hard', category: 'adjective' },
  { word: 'HUOMAAVAINEN', translation: 'considerate', translation_es: 'considerado', translation_sv: 'omtänksam', difficulty: 'hard', category: 'adjective' },
  { word: 'AVULIAS', translation: 'helpful', translation_es: 'servicial', translation_sv: 'hjälpsam', difficulty: 'hard', category: 'adjective' },
  { word: 'KUNNIANHIMOINEN', translation: 'ambitious', translation_es: 'ambicioso', translation_sv: 'ambitiös', difficulty: 'hard', category: 'adjective' },
  { word: 'OPTIMISTINEN', translation: 'optimistic', translation_es: 'optimista', translation_sv: 'optimistisk', difficulty: 'hard', category: 'adjective' },
];

/**
 * Get words filtered by difficulty level.
 */
export function getWordsByDifficulty(difficulty) {
  return words.filter((w) => w.difficulty === difficulty);
}

/**
 * Get words filtered by difficulty and categories.
 * @param {string} difficulty - 'easy', 'medium', or 'hard'
 * @param {Set<string>|string[]} categories - Set or array of category strings ('noun', 'verb', 'adjective')
 * @returns {Array} Filtered words
 */
export function getFilteredWords(difficulty, categories) {
  const cats = categories instanceof Set ? categories : new Set(categories);
  return words.filter(
    (w) => w.difficulty === difficulty && cats.has(w.category)
  );
}
